<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Permission::insert([
           [
               'name'=>'manage_settings',
               'permission_group_id'=>'10'
           ],
     /*       [
                'name'=>'manage_forms',
                'permission_group_id'=>'9'
            ],*/
            //orders
            [
                'name'=>'view_orders',
                'permission_group_id'=>'1'
            ],
            [
                'name'=>'view_order',
                'permission_group_id'=>'1'
            ],
            [
                'name'=>'create_order',
                'permission_group_id'=>'1'
            ],
            [
                'name'=>'edit_order',
                'permission_group_id'=>'1'
            ],
            [
                'name'=>'delete_order',
                'permission_group_id'=>'1'
            ],
            //EMPLOYERS
            [
                'name'=>'view_employers',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'view_employer',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'create_employer',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'edit_employer',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'delete_employer',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'view_employer_notes',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'view_employer_note',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'create_employer_note',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'edit_employer_note',
                'permission_group_id'=>'2'
            ],
            [
                'name'=>'delete_employer_note',
                'permission_group_id'=>'2'
            ],
            //Candiddate
            [
                'name'=>'view_candidates',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'view_candidate',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'create_candidate',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'edit_candidate',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'delete_candidate',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'view_candidate_notes',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'view_candidate_note',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'create_candidate_note',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'edit_candidate_note',
                'permission_group_id'=>'3'
            ],
            [
                'name'=>'delete_candidate_note',
                'permission_group_id'=>'3'
            ],
            //INVOICES
            [
                'name'=>'view_invoices',
                'permission_group_id'=>'4'
            ],
            [
                'name'=>'view_invoice',
                'permission_group_id'=>'4'
            ],
            [
                'name'=>'approve_invoice',
                'permission_group_id'=>'4'
            ],
            [
                'name'=>'edit_invoice',
                'permission_group_id'=>'4'
            ],
            [
                'name'=>'create_invoice',
                'permission_group_id'=>'4'
            ],
            [
                'name'=>'delete_invoice',
                'permission_group_id'=>'4'
            ],
            //Vacancies
            [
                'name'=>'view_vacancies',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'view_vacancy',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'create_vacancy',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'edit_vacancy',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'delete_vacancy',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'view_applications',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'view_application',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'shortlist_application',
                'permission_group_id'=>'5'
            ],
            [
                'name'=>'delete_application',
                'permission_group_id'=>'5'
            ],
            //Articles
            [
                'name'=>'view_articles',
                'permission_group_id'=>'8'
            ],
            [
                'name'=>'view_article',
                'permission_group_id'=>'8'
            ],
            [
                'name'=>'create_article',
                'permission_group_id'=>'8'
            ],
            [
                'name'=>'edit_article',
                'permission_group_id'=>'8'
            ],
            [
                'name'=>'delete_article',
                'permission_group_id'=>'8'
            ],



        ]);
    }
}
