<?php 

return [
    'dashboard' => '계기반',
    'orders' => '명령',
    'employers' => '고용주',
    'candidates' => '응시자',
    'invoices' => '송장',
    'vacancies' => '공실',
    'messaging' => '메시징',
    'blog' => '블로그',
    'articles' => '조항',
    'forms' => '양식',
    'settings' => '설정',
    'general' => '일반',
    'currency' => '통화',
    'language' => '언어',
    'email-settings' => '이메일 설정',
    'social-login' => '소셜 로그인',
    'logo-icon' => '로고 / 아이콘',
    'administrators' => '관리자',
    'mailchimp-settings' => '메일 침프 설정',
    'payment-methods' => '지불 방법',
    'order-form' => '주문 용지',
    'employer-profile' => '고용주 프로필',
    'candidate-profile' => '후보자 프로필',
    'all-candidates' => '모든 후보자',
    'shortlisted-candidates' => '최종 후보자',
    'employed-candidates' => '취업 지원자',
    'public-candidates' => '공개 후보',
    'create-candidate' => '후보자 작성',
    'categories' => '카테고리',
    'create-employer' => '고용주 만들기',
    'all-employers' => '모든 고용주',
    'active-employers' => '활동적인 고용주',
    'inactive-employers' => '비 활동 고용주',
    'employments' => '게재 위치',
    'order-settings' => '주문 설정',
    'create-order' => '주문 작성',
    'all-orders' => '모든 주문',
    'pending-orders' => '주문을 보류',
    'in-progress-orders' => '진행중인 주문',
    'completed-orders' => '완료된 주문',
    'cancelled-orders' => '취소 된 주문',
    'emails' => '이메일',
    'email' => '이메일',
];