<?php 

return [
    'welcome-heading' => '환영 제목',
    'welcome-message' => '환영 메시지',
    'show-order-form' => '주문 양식 표시 버튼',
    'show-browse-profiles' => '프로파일 찾아보기 단추 표시',
    'text' => '본문',
    'show-login-form' => '로그인 양식 표시',
    'show-register-form' => '등록 버튼 표시',
    'sort-order' => '정렬 순서',
    'latest-profiles' => '최신 프로필',
    'random' => '무작위',
    'candidate-limit' => '후보자 한도',
    'navigation-background' => '탐색 배경색',
    'navigation-text-color' => '탐색 텍스트 색상',
    'footer-background' => '바닥 글 배경색',
    'footer-text-color' => '바닥 글 텍스트 색상',
    'credits' => '크레딧',
    'office-hours' => '근무 시간',
    'social' => '사회적인',
    'background-color' => '배경색',
    'background-image' => '배경 이미지',
    'font-color' => '폰트 색깔',
    'about-us' => '회사 소개',
    'image' => '영상',
    'slide-heading' => '슬라이드 제목',
    'slide-text' => '슬라이드 텍스트',
    'top-heading' => '상단 제목',
    'sub-heading' => '소제목',
    'heading' => '표제',
    'button-text' => '버튼 텍스트',
    'button-url' => '버튼 URL',
    'post-limit' => '게시 한도',
    'newsletter-code' => '뉴스 레터 코드',
    'search' => '후보자 검색',
    'newsletter' => '뉴스 레터',
    'previous' => '이전',
    'next' => '다음',
    'read-more' => '더 읽어보기',
    'view-blog' => '블로그보기',
    'about-heading' => '제목 정보',
    'about-text' => '텍스트',
    'credits-section' => '크레딧 섹션',
    'border-color' => '테두리 색',
    'floating-icons' => '떠 다니는 아이콘 표시?',
    'credits-text' => '크레딧 텍스트',
];