<?php 

return [
    'captcha' => '보안 문자 이미지에 올바른 코드를 입력하십시오',
    'accepted' => ': 속성을 수락해야합니다.',
    'active_url' => ': attribute는 유효한 URL이 아닙니다.',
    'after' => ': attribute는 : date 이후의 날짜 여야합니다.',
    'after_or_equal' => ': attribute는 : date 이후의 날짜 여야합니다.',
    'alpha' => ': 속성에는 문자 만 포함될 수 있습니다.',
    'alpha_dash' => ': 속성에는 문자, 숫자, 대시 및 밑줄 만 포함될 수 있습니다.',
    'alpha_num' => ': 속성에는 문자와 숫자 만 포함될 수 있습니다.',
    'array' => ': attribute는 배열이어야합니다.',
    'before' => ': attribute는 : date 이전의 날짜 여야합니다.',
    'before_or_equal' => ': attribute는 : date 이전의 날짜 여야합니다.',
    'between' => [
        'numeric' => ': attribute는 : min과 : max 사이에 있어야합니다.',
        'file' => ': attribute는 : min과 : max kilobyte 사이 여야합니다.',
        'string' => ': attribute는 : min과 : max 사이 여야합니다.',
        'array' => ': attribute는 : min과 : max 사이에 있어야합니다.',
    ],
    'boolean' => ': attribute 필드는 true 또는 false 여야합니다.',
    'confirmed' => ': 속성 확인이 일치하지 않습니다.',
    'date' => ': attribute가 유효한 날짜가 아닙니다.',
    'date_equals' => ': attribute는 : date와 같은 날짜 여야합니다.',
    'date_format' => ': attribute가 : format 형식과 일치하지 않습니다.',
    'different' => ': attribute와 : other는 달라야합니다.',
    'digits' => ': attribute는 : digits 숫자 여야합니다.',
    'digits_between' => ': attribute는 : min과 : max 사이 여야합니다.',
    'dimensions' => ': attribute의 이미지 크기가 잘못되었습니다.',
    'distinct' => ': attribute 필드에는 중복 값이 ​​있습니다.',
    'email' => ': attribute는 유효한 이메일 주소 여야합니다.',
    'ends_with' => ': attribute는 다음 중 하나로 끝나야합니다. : values',
    'exists' => '선택한 : 속성이 유효하지 않습니다.',
    'file' => ': attribute는 파일이어야합니다.',
    'filled' => ': attribute 필드는 값을 가져야합니다.',
    'gt' => [
        'numeric' => ': attribute는 : value보다 커야합니다.',
        'file' => ': attribute는 : value 킬로바이트보다 커야합니다.',
        'string' => ': attribute는 : value 문자보다 커야합니다.',
        'array' => ': attribute에는 : value 개 이상의 항목이 있어야합니다.',
    ],
    'gte' => [
        'numeric' => ': attribute는 : value보다 크거나 같아야합니다.',
        'file' => ': attribute는 : value 킬로바이트 이상이어야합니다.',
        'string' => ': attribute는 : value 문자보다 크거나 같아야합니다.',
        'array' => ': attribute에는 : value 항목 이상이 있어야합니다.',
    ],
    'image' => ': attribute는 이미지 여야합니다.',
    'in' => '선택한 : 속성이 유효하지 않습니다.',
    'in_array' => ': attribute 필드는 : other에 없습니다.',
    'integer' => ': attribute는 정수 여야합니다.',
    'ip' => ': attribute는 유효한 IP 주소 여야합니다.',
    'ipv4' => ': attribute는 유효한 IPv4 주소 여야합니다.',
    'ipv6' => ': attribute는 유효한 IPv6 주소 여야합니다.',
    'json' => ': attribute는 유효한 JSON 문자열이어야합니다.',
    'lt' => [
        'numeric' => ': attribute는 : value보다 작아야합니다.',
        'file' => ': attribute는 : value 킬로바이트보다 작아야합니다.',
        'string' => ': attribute는 : value 문자보다 작아야합니다.',
        'array' => ': attribute는 : value 항목보다 작아야합니다.',
    ],
    'lte' => [
        'numeric' => ': attribute는 : value보다 작거나 같아야합니다.',
        'file' => ': attribute는 : value 킬로바이트 이하 여야합니다.',
        'string' => ': attribute는 : value 문자보다 작거나 같아야합니다.',
        'array' => ': attribute는 : value 항목을 초과하지 않아야합니다.',
    ],
    'max' => [
        'numeric' => ': attribute는 : max보다 클 수 없습니다.',
        'file' => ': attribute는 : max 킬로바이트를 초과 할 수 없습니다.',
        'string' => ': attribute는 : max자를 초과 할 수 없습니다.',
        'array' => ': attribute는 : max 개를 초과 할 수 없습니다.',
    ],
    'mimes' => ': attribute는 : values ​​유형의 파일이어야합니다.',
    'mimetypes' => ': attribute는 : values ​​유형의 파일이어야합니다.',
    'min' => [
        'numeric' => ': attribute는 최소한 : min이어야합니다.',
        'file' => ': attribute는 최소한 : min KB 이상이어야합니다.',
        'string' => ': attribute는 최소한 : min 문자 여야합니다.',
        'array' => ': attribute에는 최소한 : min 항목이 있어야합니다.',
    ],
    'not_in' => '선택한 : 속성이 유효하지 않습니다.',
    'not_regex' => ': attribute 형식이 유효하지 않습니다.',
    'numeric' => ': attribute는 숫자 여야합니다.',
    'password' => '비밀번호가 잘못되었습니다.',
    'present' => ': attribute 필드가 있어야합니다.',
    'regex' => ': attribute 형식이 유효하지 않습니다.',
    'required' => ': attribute 필드는 필수입니다.',
    'required_if' => ': attribute 필드는 : other가 : value 인 경우 필수입니다.',
    'required_unless' => ': other가 : values에 있지 않으면 : attribute 필드가 필요합니다.',
    'required_with' => ': attribute 필드는 : values가있을 때 필요합니다.',
    'required_with_all' => ': attribute 필드는 : values가있을 때 필요합니다.',
    'required_without' => ': attribute 필드는 : values가 없을 때 필요합니다.',
    'required_without_all' => ': attribute 필드는 : values가 없으면 필수입니다.',
    'same' => ': attribute 및 : other는 일치해야합니다.',
    'size' => [
        'numeric' => ': attribute는 : size 여야합니다.',
        'file' => ': attribute는 : size 킬로바이트 여야합니다.',
        'string' => ': attribute는 : size 문자 여야합니다.',
        'array' => ': attribute는 : size 항목을 포함해야합니다.',
    ],
    'starts_with' => ': attribute는 다음 중 하나로 시작해야합니다. : values',
    'string' => ': attribute는 문자열이어야합니다.',
    'timezone' => ': attribute는 유효한 영역이어야합니다.',
    'unique' => ': attribute는 이미 사용되었습니다.',
    'uploaded' => ': 속성 업로드에 실패했습니다.',
    'url' => ': attribute 형식이 유효하지 않습니다.',
    'uuid' => ': attribute는 유효한 UUID 여야합니다.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => '맞춤 메시지',
        ],
    ],
    'attributes' => '',
];