<?php 

return [
    'dashboard' => 'kontrolna ploča',
    'orders' => 'Narudžbe',
    'employers' => 'poslodavci',
    'candidates' => 'kandidati',
    'invoices' => 'računi',
    'vacancies' => 'Slobodna radna mjesta',
    'messaging' => 'Poruke',
    'blog' => 'Blog',
    'articles' => 'Članci',
    'forms' => 'obrasci',
    'settings' => 'postavke',
    'general' => 'Općenito',
    'currency' => 'Valuta',
    'language' => 'Jezik',
    'email-settings' => 'Postavke e-pošte',
    'social-login' => 'Društvena prijava',
    'logo-icon' => 'Logo / Ikona',
    'administrators' => 'administratori',
    'mailchimp-settings' => 'Postavke Mailchimp-a',
    'payment-methods' => 'Metode Plačanja',
    'order-form' => 'Obrazac za narudžbu',
    'employer-profile' => 'Profil poslodavca',
    'candidate-profile' => 'Profil kandidata',
    'all-candidates' => 'Svi kandidati',
    'shortlisted-candidates' => 'Kandidati u užem izboru',
    'employed-candidates' => 'Zaposleni kandidati',
    'public-candidates' => 'Javni kandidati',
    'create-candidate' => 'Stvorite kandidata',
    'categories' => 'Kategorije',
    'create-employer' => 'Stvorite poslodavca',
    'all-employers' => 'Svi poslodavci',
    'active-employers' => 'Aktivni poslodavci',
    'inactive-employers' => 'Neaktivni poslodavci',
    'employments' => 'plasmani',
    'order-settings' => 'Postavke narudžbe',
    'create-order' => 'Stvorite red',
    'all-orders' => 'Sve narudžbe',
    'pending-orders' => 'Naredbe na čekanju',
    'in-progress-orders' => 'U tijeku su narudžbe',
    'completed-orders' => 'Izvršene narudžbe',
    'cancelled-orders' => 'Otkazane narudžbe',
    'emails' => 'E-pošta',
    'email' => 'E-mail',
];