<?php 

return [
    'welcome-heading' => 'Naslov dobrodošlice',
    'welcome-message' => 'Poruka dobrodošlice',
    'show-order-form' => 'Gumb za prikazivanje narudžbe',
    'show-browse-profiles' => 'Prikaži gumb Pregledavanje profila',
    'text' => 'Tekst',
    'show-login-form' => 'Prikaži obrazac za prijavu',
    'show-register-form' => 'Prikaži gumbe za registraciju',
    'sort-order' => 'Poredaj Red',
    'latest-profiles' => 'Najnoviji profili',
    'random' => 'slučajan',
    'candidate-limit' => 'Ograničenje kandidata',
    'navigation-background' => 'Boja pozadine navigacije',
    'navigation-text-color' => 'Boja teksta za navigaciju',
    'footer-background' => 'Boja pozadine podnožja',
    'footer-text-color' => 'Boja teksta podnožja |',
    'credits' => 'krediti',
    'office-hours' => 'Radno vrijeme',
    'social' => 'socijalni',
    'background-color' => 'Boja pozadine',
    'background-image' => 'Pozadinska slika',
    'font-color' => 'Boja fonta',
    'about-us' => 'O nama',
    'image' => 'Slika',
    'slide-heading' => 'Klizanje naslova',
    'slide-text' => 'Tekst dijapozitiva',
    'top-heading' => 'Glavni naslov',
    'sub-heading' => 'Podnaslov',
    'heading' => 'Naslov',
    'button-text' => 'Tekst gumba',
    'button-url' => 'URL gumba',
    'post-limit' => 'Ograniči datum',
    'newsletter-code' => 'Kôd biltena',
    'search' => 'Traženje kandidata',
    'newsletter' => 'Bilten',
    'previous' => 'prijašnji',
    'next' => 'Sljedeći',
    'read-more' => 'Čitaj više',
    'view-blog' => 'Pogledajte blog',
    'about-heading' => 'O naslovu',
    'about-text' => 'O tekstu',
    'credits-section' => 'Odjeljak za kredite',
    'border-color' => 'Boja obruba',
    'floating-icons' => 'Prikaži plutajuće ikone?',
    'credits-text' => 'Tekst kredita',
];