<?php 

return [
    'captcha' => 'Unesite točan kôd na CAPTCHA slici',
    'accepted' => 'Atribut: mora biti prihvaćen.',
    'active_url' => 'Atribut:attribute nije važeći URL.',
    'after' => 'Atribut: mora biti datum nakon: datum.',
    'after_or_equal' => 'Atribut: mora biti datum nakon ili datum jednak: datumu.',
    'alpha' => 'Atribut:attribute može sadržavati samo slova.',
    'alpha_dash' => 'Atribut: može sadržavati samo slova, brojeve, crtice i podvlake.',
    'alpha_num' => 'Atribut:attribute može sadržavati samo slova i brojeve.',
    'array' => 'Atribut:attribute mora biti niz.',
    'before' => 'Atribut: mora biti datum prije: datum.',
    'before_or_equal' => 'Atribut: mora biti datum prije ili jednak: datumu.',
    'between' => [
        'numeric' => 'Atribut: mora biti između: min i: max.',
        'file' => 'Atribut: mora biti između: min i: max kilobajta.',
        'string' => 'Atribut: mora biti između: min i: max znakova.',
        'array' => 'Atribut: mora imati između: min i: max stavki.',
    ],
    'boolean' => 'Polje: atribut mora biti istinito ili lažno.',
    'confirmed' => 'Potvrda: atribut ne odgovara.',
    'date' => 'Atribut:attribute nije važeći datum.',
    'date_equals' => 'Atribut: mora biti datum jednak: datumu.',
    'date_format' => 'Atribut: ne odgovara formatu: formatu.',
    'different' => ': Atribut i: ostali moraju biti različiti.',
    'digits' => 'Atribut: mora biti: znamenke znamenke.',
    'digits_between' => 'Atribut: mora biti između: min i: max znamenki.',
    'dimensions' => 'Atribut:attribute ima nevažeće dimenzije slike.',
    'distinct' => 'Polje: atribut ima dvostruku vrijednost.',
    'email' => 'Atribut: mora biti valjana adresa e-pošte.',
    'ends_with' => 'Atribut: mora završiti jednim od sljedećeg:attribute vrijednosti',
    'exists' => 'Odabrani: atribut nije važeći.',
    'file' => 'Atribut:attribute mora biti datoteka.',
    'filled' => 'Polje: atribut mora imati vrijednost.',
    'gt' => [
        'numeric' => 'Atribut: mora biti veći od: vrijednosti.',
        'file' => 'Atribut: mora biti veći od: kilobajta vrijednosti.',
        'string' => 'Atribut: mora biti veći od: znakova vrijednosti.',
        'array' => 'Atribut: mora imati više od: vrijednosnih predmeta.',
    ],
    'gte' => [
        'numeric' => 'Atribut: mora biti veći ili jednak: vrijednost.',
        'file' => 'Atribut: mora biti veći ili jednak: kilobajti vrijednosti.',
        'string' => 'Atribut: mora biti veći ili jednak: znakovi vrijednosti.',
        'array' => 'Atribut: mora imati: stavke vrijednosti ili više.',
    ],
    'image' => 'Atribut:attribute mora biti slika.',
    'in' => 'Odabrani: atribut nije važeći.',
    'in_array' => 'Polje: atribut ne postoji u: ostalo.',
    'integer' => 'Atribut: mora biti cijeli broj.',
    'ip' => 'Atribut: mora biti valjana IP adresa.',
    'ipv4' => 'Atribut: mora biti valjana IPv4 adresa.',
    'ipv6' => 'Atribut: mora biti valjana IPv6 adresa.',
    'json' => 'Atribut: mora biti važeći JSON niz.',
    'lt' => [
        'numeric' => 'Atribut: mora biti manji od: vrijednosti.',
        'file' => 'Atribut: mora biti manji od: kilobajta vrijednosti.',
        'string' => 'Atribut: mora biti manji od: vrijednosti znakova.',
        'array' => 'Atribut: mora imati manje od: vrijednosnih stavki.',
    ],
    'lte' => [
        'numeric' => 'Atribut: mora biti manji ili jednak: vrijednost.',
        'file' => 'Atribut: mora biti manji ili jednak: kilobajti vrijednosti.',
        'string' => 'Atribut: mora biti manji ili jednak: znakovi vrijednosti.',
        'array' => 'Atribut: ne smije imati više od: vrijednosti vrijednosti.',
    ],
    'max' => [
        'numeric' => 'Atribut: ne smije biti veći od: max.',
        'file' => 'Atribut: ne smije biti veći od: max kilobajta.',
        'string' => 'Atribut: ne smije biti veći od: maks. Znakova.',
        'array' => 'Atribut: ne može imati više od: najviše stavki.',
    ],
    'mimes' => 'Atribut: mora biti datoteka tipa:attribute vrijednosti.',
    'mimetypes' => 'Atribut: mora biti datoteka tipa:attribute vrijednosti.',
    'min' => [
        'numeric' => 'Atribut: mora biti najmanje: min.',
        'file' => 'Atribut: mora biti najmanje: min kilobajta.',
        'string' => 'Atribut: mora imati najmanje: min znakova.',
        'array' => 'Atribut: mora imati najmanje: min stavki.',
    ],
    'not_in' => 'Odabrani: atribut nije važeći.',
    'not_regex' => 'Format: atribut nije valjan.',
    'numeric' => 'Atribut:attribute mora biti broj.',
    'password' => 'Lozinka je netočna.',
    'present' => 'Mora biti prisutno polje: atribut.',
    'regex' => 'Format: atribut nije valjan.',
    'required' => 'Polje: atribut je obavezno.',
    'required_if' => 'Polje: atribut obvezno je kada je: ostalo: vrijednost.',
    'required_unless' => 'Polje: atribut obvezno je osim ako je: ostalo: vrijednosti.',
    'required_with' => 'Polje: atribut obvezno je kada su prisutne: vrijednosti.',
    'required_with_all' => 'Polje: atribut obvezno je kada su: vrijednosti prisutne.',
    'required_without' => 'Polje: atribut obvezno je kada: vrijednosti nisu prisutne.',
    'required_without_all' => 'Polje: atribut obvezno je kada nijedna od: vrijednosti nije prisutna.',
    'same' => ': Atribut i: ostali moraju se podudarati.',
    'size' => [
        'numeric' => 'Atribut: mora biti: veličina.',
        'file' => 'Atribut: mora biti: veličina kilobajta.',
        'string' => 'Atribut: mora biti: veličina znakova.',
        'array' => 'Atribut: mora sadržavati: stavke veličine.',
    ],
    'starts_with' => 'Atribut: mora početi s jednim od sljedećeg:attribute vrijednosti',
    'string' => 'Atribut: mora biti niz.',
    'timezone' => 'Atribut: mora biti valjana zona.',
    'unique' => 'Atribut:attribute već je zauzet.',
    'uploaded' => 'Prijenos atributa: nije uspio.',
    'url' => 'Format: atribut nije valjan.',
    'uuid' => 'Atribut: mora biti važeći UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'prilagođene poruke',
        ],
    ],
    'attributes' => '',
];