<?php 

return [
    'dashboard' => 'Papan Pemuka',
    'orders' => 'Pesanan',
    'employers' => 'Majikan',
    'candidates' => 'Calon',
    'invoices' => 'Invois',
    'vacancies' => 'Kekosongan',
    'messaging' => 'Pemesejan',
    'blog' => 'Blog',
    'articles' => 'Artikel',
    'forms' => 'Bentuk',
    'settings' => 'Tetapan',
    'general' => 'Am',
    'currency' => 'Mata Wang',
    'language' => 'Bahasa',
    'email-settings' => 'Tetapan E-mel',
    'social-login' => 'Log masuk Sosial',
    'logo-icon' => 'Logo / Ikon',
    'administrators' => 'Pentadbir',
    'mailchimp-settings' => 'Tetapan Mailchimp',
    'payment-methods' => 'cara bayaran',
    'order-form' => 'Borang pesanan',
    'employer-profile' => 'Profil Majikan',
    'candidate-profile' => 'Profil Calon',
    'all-candidates' => 'Semua Calon',
    'shortlisted-candidates' => 'Calon yang disenarai pendek',
    'employed-candidates' => 'Calon Bekerja',
    'public-candidates' => 'Calon Awam',
    'create-candidate' => 'Buat Calon',
    'categories' => 'Kategori',
    'create-employer' => 'Buat Majikan',
    'all-employers' => 'Semua Majikan',
    'active-employers' => 'Majikan Aktif',
    'inactive-employers' => 'Majikan Tidak Aktif',
    'employments' => 'Penempatan',
    'order-settings' => 'Tetapan Pesanan',
    'create-order' => 'Buat Pesanan',
    'all-orders' => 'Semua Pesanan',
    'pending-orders' => 'Pesanan Belum Selesai',
    'in-progress-orders' => 'Dalam Perintah Progress',
    'completed-orders' => 'Pesanan Selesai',
    'cancelled-orders' => 'Pesanan yang Dibatalkan',
    'emails' => 'E-mel',
    'email' => 'E-mel',
];