<?php 

return [
    'dashboard' => 'Dasbor',
    'orders' => 'Pesanan',
    'employers' => 'Pengusaha',
    'candidates' => 'Calon',
    'invoices' => 'Faktur',
    'vacancies' => 'Lowongan',
    'messaging' => 'Olahpesan',
    'blog' => 'Blog',
    'articles' => 'Artikel',
    'forms' => 'Formulir',
    'settings' => 'Pengaturan',
    'general' => 'Umum',
    'currency' => 'Mata uang',
    'language' => 'Bahasa',
    'email-settings' => 'pengaturan email',
    'social-login' => 'Login Sosial',
    'logo-icon' => 'Logo / Ikon',
    'administrators' => 'Administrator',
    'mailchimp-settings' => 'Pengaturan MailChimp',
    'payment-methods' => 'cara Pembayaran',
    'order-form' => 'Formulir pemesanan',
    'employer-profile' => 'Profil Pemberi Kerja',
    'candidate-profile' => 'Profil Kandidat',
    'all-candidates' => 'Semua Kandidat',
    'shortlisted-candidates' => 'Kandidat terpilih',
    'employed-candidates' => 'Calon yang Dipekerjakan',
    'public-candidates' => 'Calon Publik',
    'create-candidate' => 'Buat Kandidat',
    'categories' => 'Kategori',
    'create-employer' => 'Buat Majikan',
    'all-employers' => 'Semua Pengusaha',
    'active-employers' => 'Pengusaha aktif',
    'inactive-employers' => 'Pengusaha Tidak Aktif',
    'employments' => 'Penempatan',
    'order-settings' => 'Pengaturan Pemesanan',
    'create-order' => 'Buat Pesanan',
    'all-orders' => 'Semua perintah',
    'pending-orders' => 'Pesanan Tertunda',
    'in-progress-orders' => 'Dalam Pesanan Progress',
    'completed-orders' => 'Pesanan yang Selesai',
    'cancelled-orders' => 'Pesanan yang Dibatalkan',
    'emails' => 'Email',
    'email' => 'Surel',
];