<?php 

return [
    'captcha' => 'Zadejte správný kód na obrázku CAPTCHA',
    'accepted' => 'Atribut: musí být přijat.',
    'active_url' => 'Atribut: není platná adresa URL.',
    'after' => 'Atribut: musí být datum po: date.',
    'after_or_equal' => 'Atribut: musí být datum následující nebo stejné jako: date.',
    'alpha' => 'Atribut: může obsahovat pouze písmena.',
    'alpha_dash' => 'Atribut: může obsahovat pouze písmena, čísla, pomlčky a podtržítka.',
    'alpha_num' => 'Atribut: může obsahovat pouze písmena a čísla.',
    'array' => 'Atribut: musí být pole.',
    'before' => 'Atribut: musí být datum před: date.',
    'before_or_equal' => 'Atribut: musí být datum před nebo rovno: date.',
    'between' => [
        'numeric' => 'Atribut: musí být mezi: min a: max.',
        'file' => 'Atribut: musí být mezi: min a: max. Kilobajty.',
        'string' => 'Atribut: musí být mezi: min a: max znaky.',
        'array' => 'Atribut: musí mít mezi: min a: max položkami.',
    ],
    'boolean' => 'Pole atributu musí být true nebo false.',
    'confirmed' => 'Potvrzení atributu: nesouhlasí.',
    'date' => 'Atribut: není platné datum.',
    'date_equals' => 'Atribut: musí být datum rovné: date.',
    'date_format' => 'Atribut: neodpovídá formátu: format.',
    'different' => 'Atribut: a musí být jiné.',
    'digits' => 'Atribut: musí být: číslice číslice.',
    'digits_between' => 'Atribut: musí být mezi: min a: max. Číslicemi.',
    'dimensions' => 'Atribut: má neplatné rozměry obrázku.',
    'distinct' => 'Pole atributu má duplicitní hodnotu.',
    'email' => 'Atribut: musí být platná e-mailová adresa.',
    'ends_with' => 'Atribut: musí končit jednou z následujících hodnot:attribute',
    'exists' => 'Atribut vybraný: je neplatný.',
    'file' => 'Atribut: musí být soubor.',
    'filled' => 'Pole atributu musí mít hodnotu.',
    'gt' => [
        'numeric' => 'Atribut: musí být větší než: value.',
        'file' => 'Atribut: musí být větší než: hodnota kilobajtů.',
        'string' => 'Atribut: musí být větší než: hodnotové znaky.',
        'array' => 'Atribut: musí obsahovat více než: hodnotových položek.',
    ],
    'gte' => [
        'numeric' => 'Atribut: musí být větší nebo roven: value.',
        'file' => 'Atribut: musí být větší nebo roven: hodnota kilobajtů.',
        'string' => 'Atribut: musí být větší nebo roven: value.',
        'array' => 'Atribut: musí mít: hodnotové položky nebo více.',
    ],
    'image' => 'Atribut: musí být obrázek.',
    'in' => 'Atribut vybraný: je neplatný.',
    'in_array' => 'Pole atributů neexistuje v: other.',
    'integer' => 'Atribut: musí být celé číslo.',
    'ip' => 'Atribut: musí být platná adresa IP.',
    'ipv4' => 'Atribut: musí být platná adresa IPv4.',
    'ipv6' => 'Atribut: musí být platná adresa IPv6.',
    'json' => 'Atribut: musí být platný řetězec JSON.',
    'lt' => [
        'numeric' => 'Atribut: musí být menší než: value.',
        'file' => 'Atribut: musí být menší než: hodnota kilobajtů.',
        'string' => 'Atribut: musí být menší než: hodnotové znaky.',
        'array' => 'Atribut: musí obsahovat méně než: hodnotové položky.',
    ],
    'lte' => [
        'numeric' => 'Atribut: musí být menší nebo roven: value.',
        'file' => 'Atribut: musí být menší nebo roven: hodnota kilobajtů.',
        'string' => 'Atribut: musí být menší nebo roven hodnotovým znakům.',
        'array' => 'Atribut: nesmí obsahovat více než: hodnotových položek.',
    ],
    'max' => [
        'numeric' => 'Atribut: nesmí být větší než: max.',
        'file' => 'Atribut: nesmí být větší než: max. Kilobajtů.',
        'string' => 'Atribut: nesmí být větší než: max. Znaků.',
        'array' => 'Atribut: nesmí obsahovat více než: max položek.',
    ],
    'mimes' => 'Atribut: musí být soubor hodnot typu:attribute',
    'mimetypes' => 'Atribut: musí být soubor hodnot typu:attribute',
    'min' => [
        'numeric' => 'Atribut: musí být alespoň: min.',
        'file' => 'Atribut: musí být alespoň: min kilobajtů.',
        'string' => 'Atribut: musí být alespoň: min znaků.',
        'array' => 'Atribut: musí obsahovat alespoň: min položek.',
    ],
    'not_in' => 'Atribut vybraný: je neplatný.',
    'not_regex' => 'Formát atributu: je neplatný.',
    'numeric' => 'Atribut: musí být číslo.',
    'password' => 'Heslo je nesprávné.',
    'present' => 'Musí být přítomno pole: attribute.',
    'regex' => 'Formát atributu: je neplatný.',
    'required' => 'Pole: attribute je povinné.',
    'required_if' => 'Pole: attribute je povinné, když: other is: value.',
    'required_unless' => 'Pole: attribute je povinné, pokud: other je v: value.',
    'required_with' => 'Pole atributů je povinné, pokud jsou k dispozici: hodnoty.',
    'required_with_all' => 'Pole atributů je povinné, jsou-li k dispozici: hodnoty.',
    'required_without' => 'Pole atributů je povinné, když: hodnoty nejsou k dispozici.',
    'required_without_all' => 'Pole atributů je povinné, pokud není přítomna žádná z hodnot.',
    'same' => 'Atribut: a a other musí odpovídat.',
    'size' => [
        'numeric' => 'Atribut: musí být: velikost.',
        'file' => 'Atribut: musí být: velikost kilobajtů.',
        'string' => 'Atribut: musí být: velikost znaků.',
        'array' => 'Atribut: musí obsahovat: size items.',
    ],
    'starts_with' => 'Atribut: musí začínat jedním z následujících hodnot:attribute',
    'string' => 'Atribut: musí být řetězec.',
    'timezone' => 'Atribut: musí být platná zóna.',
    'unique' => 'Atribut: již byl převzat.',
    'uploaded' => 'Atribut: se nepodařilo nahrát.',
    'url' => 'Formát atributu: je neplatný.',
    'uuid' => 'Atribut: musí být platný UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'vlastní zpráva',
        ],
    ],
    'attributes' => '',
];