<?php 

return [
    'dashboard' => 'Deska rozdzielcza',
    'orders' => 'Zamówienia',
    'employers' => 'Pracodawcy',
    'candidates' => 'Kandydaci',
    'invoices' => 'Faktury',
    'vacancies' => 'Wakaty',
    'messaging' => 'Wiadomości',
    'blog' => 'Blog',
    'articles' => 'Artykuły',
    'forms' => 'Formularze',
    'settings' => 'Ustawienia',
    'general' => 'Generał',
    'currency' => 'Waluta',
    'language' => 'Język',
    'email-settings' => 'Ustawienia poczty e-mail',
    'social-login' => 'Login społecznościowy',
    'logo-icon' => 'Logo / ikona',
    'administrators' => 'Administratorzy',
    'mailchimp-settings' => 'Ustawienia Mailchimp',
    'payment-methods' => 'Metody Płatności',
    'order-form' => 'Formularz zamówienia',
    'employer-profile' => 'Profil pracodawcy',
    'candidate-profile' => 'Profil kandydata',
    'all-candidates' => 'Wszyscy kandydaci',
    'shortlisted-candidates' => 'Zakwalifikowani kandydaci',
    'employed-candidates' => 'Zatrudnieni kandydaci',
    'public-candidates' => 'Kandydaci publiczni',
    'create-candidate' => 'Utwórz kandydata',
    'categories' => 'Kategorie',
    'create-employer' => 'Utwórz pracodawcę',
    'all-employers' => 'Wszyscy pracodawcy',
    'active-employers' => 'Aktywni pracodawcy',
    'inactive-employers' => 'Nieaktywni pracodawcy',
    'employments' => 'Miejsca docelowe',
    'order-settings' => 'Zamów ustawienia',
    'create-order' => 'Utwórz zamówienie',
    'all-orders' => 'Wszystkie zamówienia',
    'pending-orders' => 'Oczekujące zamówienia',
    'in-progress-orders' => 'Zamówienia w toku',
    'completed-orders' => 'Zrealizowane zamówienia',
    'cancelled-orders' => 'Anulowane zamówienia',
    'emails' => 'E-maile',
    'email' => 'E-mail',
];