<?php 

return [
    'welcome-heading' => 'Приветствие заглавие',
    'welcome-message' => 'Съобщение за добре дошли',
    'show-order-form' => 'Покажи бутон за формуляр за поръчка',
    'show-browse-profiles' => 'Покажи бутона Преглед на профили',
    'text' => 'Текст',
    'show-login-form' => 'Покажете формуляра за вход',
    'show-register-form' => 'Показване на бутони за регистрация',
    'sort-order' => 'Подреди ред',
    'latest-profiles' => 'Последни профили',
    'random' => 'случаен',
    'candidate-limit' => 'Ограничение на кандидатите',
    'navigation-background' => 'Цвят на фона на навигацията',
    'navigation-text-color' => 'Цвят на навигационния текст',
    'footer-background' => 'Цвят на фона на подножието',
    'footer-text-color' => 'Цвят на текста на долния колонтитул',
    'credits' => 'Кредити',
    'office-hours' => 'Работно време',
    'social' => 'социален',
    'background-color' => 'Цвят на фона',
    'background-image' => 'Фоново изображение',
    'font-color' => 'Цвят на шрифта',
    'about-us' => 'За нас',
    'image' => 'Изображение',
    'slide-heading' => 'Слайд заглавие',
    'slide-text' => 'Слайд текст',
    'top-heading' => 'Топ заглавие',
    'sub-heading' => 'Подзаглавие',
    'heading' => 'Заглавие',
    'button-text' => 'Текст на бутон',
    'button-url' => 'URL адрес на бутона',
    'post-limit' => 'Лимит за срок',
    'newsletter-code' => 'Код на бюлетина',
    'search' => 'Търсене на кандидати',
    'newsletter' => 'Newsletter',
    'previous' => 'предишен',
    'next' => 'Следващия',
    'read-more' => 'Прочетете още',
    'view-blog' => 'Вижте блога',
    'about-heading' => 'Относно заглавието',
    'about-text' => 'Относно текста',
    'credits-section' => 'Секция за кредити',
    'border-color' => 'Цвят на границата',
    'floating-icons' => 'Показване на плаващи икони?',
    'credits-text' => 'Текст на кредити',
];