<?php 

return [
    'welcome-heading' => 'Добро пожаловать Заголовок',
    'welcome-message' => 'Приветствие',
    'show-order-form' => 'Кнопка Показать форму заказа',
    'show-browse-profiles' => 'Показать кнопку просмотра профилей',
    'text' => 'Текст',
    'show-login-form' => 'Показать форму входа',
    'show-register-form' => 'Показать кнопки регистрации',
    'sort-order' => 'Порядок сортировки',
    'latest-profiles' => 'Последние профили',
    'random' => 'случайный',
    'candidate-limit' => 'Кандидат лимит',
    'navigation-background' => 'Цвет фона навигации',
    'navigation-text-color' => 'Цвет текста навигации',
    'footer-background' => 'Цвет нижнего колонтитула',
    'footer-text-color' => 'Цвет текста нижнего колонтитула',
    'credits' => 'кредиты',
    'office-hours' => 'Рабочие часы',
    'social' => 'Социальное',
    'background-color' => 'Фоновый цвет',
    'background-image' => 'Фоновая картинка',
    'font-color' => 'Цвет шрифта',
    'about-us' => 'Насчет нас',
    'image' => 'Образ',
    'slide-heading' => 'Заголовок слайда',
    'slide-text' => 'Текст слайда',
    'top-heading' => 'Верхний заголовок',
    'sub-heading' => 'Подзаголовок',
    'heading' => 'Heading',
    'button-text' => 'Текст кнопки',
    'button-url' => 'URL кнопки',
    'post-limit' => 'Post Limit',
    'newsletter-code' => 'Код информационного бюллетеня',
    'search' => 'Поиск кандидатов',
    'newsletter' => 'Новостная рассылка',
    'previous' => 'предыдущий',
    'next' => 'следующий',
    'read-more' => 'Читать далее',
    'view-blog' => 'Просмотр блога',
    'about-heading' => 'О заголовке',
    'about-text' => 'О тексте',
    'credits-section' => 'Раздел Кредитов',
    'border-color' => 'Цвет границы',
    'floating-icons' => 'Показывать плавающие иконки?',
    'credits-text' => 'Текст кредита',
];