<?php 

return [
    'captcha' => 'Indtast den korrekte kode på CAPTCHA-billedet',
    'accepted' => 'Attributten skal accepteres.',
    'active_url' => 'Attributten er ikke en gyldig URL.',
    'after' => 'Attributten skal være en dato efter: dato.',
    'after_or_equal' => 'Attributten skal være en dato efter eller lig med: dato.',
    'alpha' => 'Attributten må kun indeholde bogstaver.',
    'alpha_dash' => 'Attributten må kun indeholde bogstaver, tal, bindestreger og understregninger.',
    'alpha_num' => 'Attributten må kun indeholde bogstaver og tal.',
    'array' => 'Attributten skal være en matrix.',
    'before' => 'Attributten skal være en dato før: dato.',
    'before_or_equal' => 'Attributten skal være en dato før eller lig med: dato.',
    'between' => [
        'numeric' => 'Attributten skal være mellem: min og: maks.',
        'file' => 'Attributten skal være mellem: min og: max kilobytes.',
        'string' => 'Attributten skal være mellem: min og: maks. Tegn.',
        'array' => 'Attributten skal have mellem: min og: maks. Poster.',
    ],
    'boolean' => 'Feltet: attribut skal være sandt eller falsk.',
    'confirmed' => 'Bekræftelsen af ​​attributten stemmer ikke overens.',
    'date' => 'Attributten er ikke en gyldig dato.',
    'date_equals' => 'Attributten skal være en dato, der er lig med: dato.',
    'date_format' => 'Attributten svarer ikke til formatet: format.',
    'different' => 'Attributten og: anden skal være forskellige.',
    'digits' => 'Attributten skal være: cifrede cifre.',
    'digits_between' => 'Attributten skal være mellem: min og: maks. Cifre.',
    'dimensions' => 'Attributten har ugyldige billeddimensioner.',
    'distinct' => 'Feltet: attribut har en duplikatværdi.',
    'email' => 'Attributten skal være en gyldig e-mail-adresse.',
    'ends_with' => 'Attributten skal slutte med en af ​​følgende:attribute værdier',
    'exists' => 'Den valgte: attribut er ugyldig.',
    'file' => 'Attributten skal være en fil.',
    'filled' => 'Feltet: attribut skal have en værdi.',
    'gt' => [
        'numeric' => 'Attributten skal være større end: værdi.',
        'file' => 'Attributten skal være større end: kilobyte.',
        'string' => 'Attributten skal være større end: værdienstegn.',
        'array' => 'Attributten skal have mere end: værdiemner.',
    ],
    'gte' => [
        'numeric' => 'Attributten skal være større end eller lig: værdi.',
        'file' => 'Attributten skal være større end eller lig: kilobyte.',
        'string' => 'Attributten skal være større end eller lig: værdienstegn.',
        'array' => 'Attributten skal have: værdiemner eller mere.',
    ],
    'image' => 'Attributten skal være et billede.',
    'in' => 'Den valgte: attribut er ugyldig.',
    'in_array' => 'Feltet: attribut findes ikke i: andet.',
    'integer' => 'Attributten skal være et heltal.',
    'ip' => 'Attributten skal være en gyldig IP-adresse.',
    'ipv4' => 'Attributten skal være en gyldig IPv4-adresse.',
    'ipv6' => 'Attributten skal være en gyldig IPv6-adresse.',
    'json' => 'Attributten skal være en gyldig JSON-streng.',
    'lt' => [
        'numeric' => 'Attributten skal være mindre end: værdi.',
        'file' => 'Attributten skal være mindre end: kilobyte.',
        'string' => 'Attributten skal være mindre end: værdienstegn.',
        'array' => 'Attributten skal have mindre end: værdiemner.',
    ],
    'lte' => [
        'numeric' => 'Attributten skal være mindre end eller lig: værdi.',
        'file' => 'Attributten skal være mindre end eller lig: kilobyte.',
        'string' => 'Attributten skal være mindre end eller lig: værdienstegn.',
        'array' => 'Attributten må ikke have mere end: værdiemner.',
    ],
    'max' => [
        'numeric' => 'Attributten må ikke være større end: max.',
        'file' => 'Attributten må ikke være større end: max kilobytes.',
        'string' => 'Attributten må ikke være større end: maks. Tegn.',
        'array' => 'Attributten har muligvis ikke mere end: maks. Poster.',
    ],
    'mimes' => 'Attributten skal være en fil af typen:attribute -værdier.',
    'mimetypes' => 'Attributten skal være en fil af typen:attribute -værdier.',
    'min' => [
        'numeric' => 'Attributten skal være mindst: min.',
        'file' => 'Attributten skal være mindst: min kilobytes.',
        'string' => 'Attributten skal mindst være: min. Tegn.',
        'array' => 'Attributten skal mindst have: min. Genstande.',
    ],
    'not_in' => 'Den valgte: attribut er ugyldig.',
    'not_regex' => 'Attributformatet er ugyldigt.',
    'numeric' => 'Attributten skal være et tal.',
    'password' => 'Adgangskoden er forkert.',
    'present' => 'Feltet: attribut skal være til stede.',
    'regex' => 'Attributformatet er ugyldigt.',
    'required' => 'Feltet: attribut er påkrævet.',
    'required_if' => 'Feltet: attribut kræves, når: andet er: værdi.',
    'required_unless' => 'Feltet: attribut er påkrævet, medmindre: andet er i: værdier.',
    'required_with' => 'Feltet: attribut er påkrævet, når: værdier er til stede.',
    'required_with_all' => 'Feltet: attribut er påkrævet, når: værdier er til stede.',
    'required_without' => 'Feltet: attribut er påkrævet, når: værdier ikke er til stede.',
    'required_without_all' => 'Feltet: attribut er påkrævet, når ingen af: værdier er til stede.',
    'same' => 'Attributten og: anden skal matche.',
    'size' => [
        'numeric' => 'Attributten skal være: størrelse.',
        'file' => 'Attributten skal være: størrelse kilobyte.',
        'string' => 'Attributten skal være: størrelsestegn.',
        'array' => 'Attributten skal indeholde: størrelseselementer.',
    ],
    'starts_with' => 'Attributten skal starte med et af følgende:attribute -værdier',
    'string' => 'Attributten skal være en streng.',
    'timezone' => 'Attributten skal være en gyldig zone.',
    'unique' => 'Attributten er allerede taget.',
    'uploaded' => 'Attributten: attributten kunne ikke uploades.',
    'url' => 'Attributformatet er ugyldigt.',
    'uuid' => 'Attributten skal være en gyldig UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-besked',
        ],
    ],
    'attributes' => '',
];