<?php 

return [
    'welcome-heading' => 'Bine ați venit Titlu',
    'welcome-message' => 'Mesaj de intampinare',
    'show-order-form' => 'Afișați butonul Formular de comandă',
    'show-browse-profiles' => 'Afișați butonul Căutare profiluri',
    'text' => 'Text',
    'show-login-form' => 'Arată formularul de autentificare',
    'show-register-form' => 'Afișare butoane de înregistrare',
    'sort-order' => 'Ordinea de sortare',
    'latest-profiles' => 'Ultimele profiluri',
    'random' => 'Aleatoriu',
    'candidate-limit' => 'Limita candidaților',
    'navigation-background' => 'Navigare Culoare de fundal',
    'navigation-text-color' => 'Culoare text de navigare',
    'footer-background' => 'Culoarea fundalului de subsol',
    'footer-text-color' => 'Culoarea textului de subsol',
    'credits' => 'credite',
    'office-hours' => 'Ore de birou',
    'social' => 'Social',
    'background-color' => 'Culoare de fundal',
    'background-image' => 'Imagine de fundal',
    'font-color' => 'Culoarea fontului',
    'about-us' => 'Despre noi',
    'image' => 'Imagine',
    'slide-heading' => 'Glisare antet',
    'slide-text' => 'Slide Text',
    'top-heading' => 'Titlu superior',
    'sub-heading' => 'Subtitrare',
    'heading' => 'Titlu',
    'button-text' => 'Butonul Text',
    'button-url' => 'URL-ul butonului',
    'post-limit' => 'Limita postului',
    'newsletter-code' => 'Codul buletinului informativ',
    'search' => 'Căutare de candidați',
    'newsletter' => 'Buletin informativ',
    'previous' => 'Anterior',
    'next' => 'Următor →',
    'read-more' => 'Citeste mai mult',
    'view-blog' => 'Vizualizați blogul',
    'about-heading' => 'Despre rubrică',
    'about-text' => 'Despre text',
    'credits-section' => 'Secțiunea Credite',
    'border-color' => 'Culoare de graniță',
    'floating-icons' => 'Afișați pictogramele plutitoare?',
    'credits-text' => 'Textul creditelor',
];