<?php 

return [
    'captcha' => 'Vă rugăm să introduceți codul corect pe imaginea CAPTCHA',
    'accepted' => 'Atributul: trebuie acceptat.',
    'active_url' => 'Atributul: nu este o adresă URL validă.',
    'after' => 'Atributul: trebuie să fie o dată după: data.',
    'after_or_equal' => 'Atributul: trebuie să fie o dată ulterioară sau egală cu: data.',
    'alpha' => 'Atributul: poate conține doar litere.',
    'alpha_dash' => 'Atributul: poate conține doar litere, numere, liniuțe și scăzute.',
    'alpha_num' => 'Atributul: poate conține doar litere și numere.',
    'array' => 'Atributul: trebuie să fie un tablou.',
    'before' => 'Atributul: trebuie să fie o dată înainte de: data.',
    'before_or_equal' => 'Atributul: trebuie să fie o dată înainte sau egală cu: data.',
    'between' => [
        'numeric' => 'Atributul: trebuie să fie între: min și: max.',
        'file' => 'Atributul: trebuie să fie între: min și: max kilobytes.',
        'string' => 'Atributul: trebuie să fie între: min și: caractere max.',
        'array' => 'Atributul: trebuie să aibă între: min și: max.',
    ],
    'boolean' => 'Câmpul: atribut trebuie să fie adevărat sau fals.',
    'confirmed' => 'Confirmarea atributului: nu se potrivește.',
    'date' => 'Atributul: nu este o dată valabilă.',
    'date_equals' => 'Atributul: trebuie să fie o dată egală cu: data.',
    'date_format' => 'Atributul: nu se potrivește cu formatul: formatul.',
    'different' => 'Atributul: și altul trebuie să fie diferite.',
    'digits' => 'Atributul: trebuie să fie: cifre cifre.',
    'digits_between' => 'Atributul: trebuie să fie între: min și: cifre max.',
    'dimensions' => 'Atributul: are dimensiuni de imagine nevalide.',
    'distinct' => 'Câmpul: atribut are o valoare duplicată.',
    'email' => 'Atributul: trebuie să fie o adresă de e-mail validă.',
    'ends_with' => 'Atributul: trebuie să se încheie cu una dintre următoarele: valori',
    'exists' => 'Atributul selectat: este nevalid.',
    'file' => 'Atributul: trebuie să fie un fișier.',
    'filled' => 'Câmpul: atribut trebuie să aibă o valoare.',
    'gt' => [
        'numeric' => 'Atributul trebuie să fie mai mare decât: valoare.',
        'file' => 'Atributul: trebuie să fie mai mare decât: valoarea kilobytes.',
        'string' => 'Atributul: trebuie să fie mai mare decât: caractere valorice.',
        'array' => 'Atributul: trebuie să aibă mai mult de: elemente de valoare.',
    ],
    'gte' => [
        'numeric' => 'Atributul trebuie să fie mai mare sau egal: valoarea.',
        'file' => 'Atributul: trebuie să fie mai mare sau egal: valoarea kilobytes.',
        'string' => 'Atributul: trebuie să fie mai mare sau egal: caractere de valoare.',
        'array' => 'Atributul: trebuie să aibă: elemente de valoare sau mai multe.',
    ],
    'image' => 'Atributul: trebuie să fie o imagine.',
    'in' => 'Atributul selectat: este nevalid.',
    'in_array' => 'Câmpul: atribut nu există în: altul.',
    'integer' => 'Atributul: trebuie să fie un număr întreg.',
    'ip' => 'Atributul: trebuie să fie o adresă IP valabilă.',
    'ipv4' => 'Atributul: trebuie să fie o adresă IPv4 validă.',
    'ipv6' => 'Atributul: trebuie să fie o adresă IPv6 validă.',
    'json' => 'Atributul: trebuie să fie un șir JSON valid.',
    'lt' => [
        'numeric' => 'Atributul: trebuie să fie mai mic decât: valoare.',
        'file' => 'Atributul: trebuie să fie mai mic decât: valoarea kilobytes.',
        'string' => 'Atributul: trebuie să fie mai mic decât: caractere valorice.',
        'array' => 'Atributul: trebuie să aibă mai puțin de: elemente de valoare.',
    ],
    'lte' => [
        'numeric' => 'Atributul: trebuie să fie mai mic sau egal: valoare.',
        'file' => 'Atributul: trebuie să fie mai mic sau egal: valoarea kilobytes.',
        'string' => 'Atributul: trebuie să fie mai mic sau egal: caractere de valoare.',
        'array' => 'Atributul: nu trebuie să aibă mai mult de: elemente de valoare.',
    ],
    'max' => [
        'numeric' => 'Atributul: nu poate fi mai mare decât: max.',
        'file' => 'Atributul: nu poate fi mai mare de: kilobiți max.',
        'string' => 'Atributul: nu poate fi mai mare de: caractere max.',
        'array' => 'Atributul: nu poate avea mai mult de: maxim de elemente.',
    ],
    'mimes' => 'Atributul: trebuie să fie un fișier de tipul:attribute valori.',
    'mimetypes' => 'Atributul: trebuie să fie un fișier de tipul:attribute valori.',
    'min' => [
        'numeric' => 'Atributul: trebuie să fie cel puțin: min.',
        'file' => 'Atributul: trebuie să fie cel puțin: min kilobiți.',
        'string' => 'Atributul: trebuie să fie cel puțin: min. Caractere.',
        'array' => 'Atributul: trebuie să aibă cel puțin: min. Elemente.',
    ],
    'not_in' => 'Atributul selectat: este nevalid.',
    'not_regex' => 'Formatul: atribut este nevalid.',
    'numeric' => 'Atributul: trebuie să fie un număr.',
    'password' => 'Parola este incorecta.',
    'present' => 'Câmpul: atribut trebuie să fie prezent.',
    'regex' => 'Formatul: atribut este nevalid.',
    'required' => 'Câmpul: atribut este obligatoriu.',
    'required_if' => 'Câmpul: atribut este necesar atunci când: altul este: valoare.',
    'required_unless' => 'Câmpul: atribut este obligatoriu dacă: altul este în: valori.',
    'required_with' => 'Câmpul: atribut este necesar atunci când: valorile sunt prezente.',
    'required_with_all' => 'Câmpul: atribut este necesar atunci când: valorile sunt prezente.',
    'required_without' => 'Câmpul: atribut este necesar atunci când: valorile nu sunt prezente.',
    'required_without_all' => 'Câmpul: atribut este necesar atunci când nu există nici una din: valori.',
    'same' => 'Atributul: și altul trebuie să se potrivească.',
    'size' => [
        'numeric' => 'Atributul trebuie să fie: mărimea.',
        'file' => 'Atributul: trebuie să fie: mărimea kilobytes.',
        'string' => 'Atributul trebuie să fie: caractere de mărime.',
        'array' => 'Atributul: trebuie să conțină: elemente de mărime.',
    ],
    'starts_with' => 'Atributul: trebuie să înceapă cu una dintre următoarele: valori',
    'string' => 'Atributul: trebuie să fie un șir.',
    'timezone' => 'Atributul: trebuie să fie o zonă validă.',
    'unique' => 'Atributul: a fost deja luat.',
    'uploaded' => 'Atributul: nu a reușit să se încarce.',
    'url' => 'Formatul: atribut este nevalid.',
    'uuid' => 'Atributul: trebuie să fie un UUID valid.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'personalizat-mesaj',
        ],
    ],
    'attributes' => '',
];