<?php 

return [
    'captcha' => 'Inserisci il codice corretto nell\'immagine CAPTCHA',
    'accepted' => 'L\'attributo: deve essere accettato.',
    'active_url' => 'L\'attributo: non è un URL valido.',
    'after' => 'L\'attributo: deve essere una data dopo: date.',
    'after_or_equal' => 'L\'attributo: deve essere una data successiva o uguale a: data.',
    'alpha' => 'L\'attributo: può contenere solo lettere.',
    'alpha_dash' => 'L\'attributo: può contenere solo lettere, numeri, trattini e trattini bassi.',
    'alpha_num' => 'L\'attributo: può contenere solo lettere e numeri.',
    'array' => 'L\'attributo: deve essere un array.',
    'before' => 'L\'attributo: deve essere una data prima di: data.',
    'before_or_equal' => 'L\'attributo: deve essere una data precedente o uguale a: date.',
    'between' => [
        'numeric' => 'L\'attributo: deve essere compreso tra: min e: max.',
        'file' => 'L\'attributo: deve essere compreso tra: min e: max kilobytes.',
        'string' => 'L\'attributo: deve essere compreso tra: min e: max caratteri.',
        'array' => 'L\'attributo: deve avere tra: min e: max articoli.',
    ],
    'boolean' => 'Il campo: attributo deve essere vero o falso.',
    'confirmed' => 'La conferma dell\'attributo: non corrisponde.',
    'date' => 'L\'attributo: non è una data valida.',
    'date_equals' => 'L\'attributo: deve essere una data uguale a: date.',
    'date_format' => 'L\'attributo: non corrisponde al formato: formato.',
    'different' => 'L\'attributo: e: other devono essere diversi.',
    'digits' => 'L\'attributo: deve essere: cifre cifre.',
    'digits_between' => 'L\'attributo: deve essere compreso tra: min e: max cifre.',
    'dimensions' => 'L\'attributo: ha dimensioni dell\'immagine non valide.',
    'distinct' => 'Il campo: attributo ha un valore duplicato.',
    'email' => 'L\'attributo: deve essere un indirizzo email valido.',
    'ends_with' => 'L\'attributo: deve terminare con uno dei seguenti:attribute valori',
    'exists' => 'L\'attributo: selezionato non è valido.',
    'file' => 'L\'attributo: deve essere un file.',
    'filled' => 'Il campo: attributo deve avere un valore.',
    'gt' => [
        'numeric' => 'L\'attributo: deve essere maggiore di: valore.',
        'file' => 'L\'attributo: deve essere maggiore di: value kilobytes.',
        'string' => 'L\'attributo: deve essere maggiore di: caratteri di valore.',
        'array' => 'L\'attributo: deve avere più di: value items.',
    ],
    'gte' => [
        'numeric' => 'L\'attributo: deve essere maggiore o uguale a: valore.',
        'file' => 'L\'attributo: deve essere maggiore o uguale a: kilobyte di valore.',
        'string' => 'L\'attributo: deve essere maggiore o uguale a: valore caratteri.',
        'array' => 'L\'attributo: must have: value items o more.',
    ],
    'image' => 'L\'attributo: deve essere un\'immagine.',
    'in' => 'L\'attributo: selezionato non è valido.',
    'in_array' => 'Il campo: attributo non esiste in: altro.',
    'integer' => 'L\'attributo: deve essere un numero intero.',
    'ip' => 'L\'attributo: deve essere un indirizzo IP valido.',
    'ipv4' => 'L\'attributo: deve essere un indirizzo IPv4 valido.',
    'ipv6' => 'L\'attributo: deve essere un indirizzo IPv6 valido.',
    'json' => 'L\'attributo: deve essere una stringa JSON valida.',
    'lt' => [
        'numeric' => 'L\'attributo: deve essere inferiore a: valore.',
        'file' => 'L\'attributo: deve essere inferiore a: value kilobytes.',
        'string' => 'L\'attributo: deve essere inferiore a: caratteri di valore.',
        'array' => 'L\'attributo: deve avere elementi inferiori a: value.',
    ],
    'lte' => [
        'numeric' => 'L\'attributo: deve essere minore o uguale a: valore.',
        'file' => 'L\'attributo: deve essere inferiore o uguale a: valore kilobyte.',
        'string' => 'L\'attributo: deve essere inferiore o uguale a: valori di caratteri.',
        'array' => 'L\'attributo: non deve avere più di: value items.',
    ],
    'max' => [
        'numeric' => 'L\'attributo: non può essere maggiore di: max.',
        'file' => 'L\'attributo: non può essere maggiore di: kilobyte max.',
        'string' => 'L\'attributo: non può essere maggiore di: max caratteri.',
        'array' => 'L\'attributo: potrebbe non avere più di: max articoli.',
    ],
    'mimes' => 'L\'attributo: deve essere un file di tipo:attribute valori.',
    'mimetypes' => 'L\'attributo: deve essere un file di tipo:attribute valori.',
    'min' => [
        'numeric' => 'L\'attributo: deve essere almeno: min.',
        'file' => 'L\'attributo: deve essere almeno: kilobyte min.',
        'string' => 'L\'attributo: deve essere almeno: caratteri min.',
        'array' => 'L\'attributo: deve contenere almeno: elementi min.',
    ],
    'not_in' => 'L\'attributo: selezionato non è valido.',
    'not_regex' => 'Il formato dell\'attributo: non è valido.',
    'numeric' => 'L\'attributo: deve essere un numero.',
    'password' => 'La password non è corretta',
    'present' => 'Il campo: attributo deve essere presente.',
    'regex' => 'Il formato dell\'attributo: non è valido.',
    'required' => 'Il campo: attributo è obbligatorio.',
    'required_if' => 'Il campo: attributo è obbligatorio quando: altro è: valore.',
    'required_unless' => 'Il campo: attributo è obbligatorio a meno che: other sia in: valori.',
    'required_with' => 'Il campo: attributo è obbligatorio quando: valori sono presenti.',
    'required_with_all' => 'Il campo: attributo è obbligatorio quando: valori sono presenti.',
    'required_without' => 'Il campo: attributo è obbligatorio quando: valori non è presente.',
    'required_without_all' => 'Il campo: attributo è obbligatorio quando nessuno di: valori è presente.',
    'same' => 'L\'attributo: e: other devono corrispondere.',
    'size' => [
        'numeric' => 'L\'attributo: deve essere: size.',
        'file' => 'L\'attributo: deve essere: dimensione kilobyte.',
        'string' => 'L\'attributo: deve essere: caratteri di dimensione.',
        'array' => 'L\'attributo: deve contenere: elementi dimensione.',
    ],
    'starts_with' => 'L\'attributo: deve iniziare con uno dei seguenti:attribute valori',
    'string' => 'L\'attributo: deve essere una stringa.',
    'timezone' => 'L\'attributo: deve essere una zona valida.',
    'unique' => 'L\'attributo: è già stato preso.',
    'uploaded' => 'Il caricamento dell\'attributo: non è riuscito.',
    'url' => 'Il formato dell\'attributo: non è valido.',
    'uuid' => 'L\'attributo: deve essere un UUID valido.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-messaggio',
        ],
    ],
    'attributes' => '',
];