<?php 

return [
    'dashboard' => 'kojelauta',
    'orders' => 'tilaukset',
    'employers' => 'työnantajat',
    'candidates' => 'ehdokkaat',
    'invoices' => 'laskut',
    'vacancies' => 'Työpaikkailmoitukset',
    'messaging' => 'Viestit',
    'blog' => 'blogi',
    'articles' => 'Artikkelit',
    'forms' => 'Lomakkeet',
    'settings' => 'asetukset',
    'general' => 'yleinen',
    'currency' => 'valuutta',
    'language' => 'Kieli',
    'email-settings' => 'Sähköpostiasetukset',
    'social-login' => 'Sosiaalinen kirjautuminen',
    'logo-icon' => 'Logo / kuvake',
    'administrators' => 'ylläpitäjät',
    'mailchimp-settings' => 'Mailchimp-asetukset',
    'payment-methods' => 'maksutavat',
    'order-form' => 'Tilauslomake',
    'employer-profile' => 'Työnantajan profiili',
    'candidate-profile' => 'Ehdokasprofiili',
    'all-candidates' => 'Kaikki ehdokkaat',
    'shortlisted-candidates' => 'Valittuihin ehdokkaisiin',
    'employed-candidates' => 'Työntekijät',
    'public-candidates' => 'Julkiset ehdokkaat',
    'create-candidate' => 'Luo ehdokas',
    'categories' => 'Luokat',
    'create-employer' => 'Luo työnantaja',
    'all-employers' => 'Kaikki työnantajat',
    'active-employers' => 'Aktiiviset työnantajat',
    'inactive-employers' => 'Passiiviset työnantajat',
    'employments' => 'mainospaikat',
    'order-settings' => 'Tilausasetukset',
    'create-order' => 'Luo tilaus',
    'all-orders' => 'Kaikki tilaukset',
    'pending-orders' => 'Odottavat tilaukset',
    'in-progress-orders' => 'Käynnissä olevat tilaukset',
    'completed-orders' => 'Valmiit tilaukset',
    'cancelled-orders' => 'Peruutetut tilaukset',
    'emails' => 'sähköpostit',
    'email' => 'Sähköposti',
];