<?php 

return [
    'welcome-heading' => 'Tervetuloa otsikko',
    'welcome-message' => 'Tervetuloviesti',
    'show-order-form' => 'Näytä tilauslomake -painike',
    'show-browse-profiles' => 'Näytä Selaa profiileja -painike',
    'text' => 'Teksti',
    'show-login-form' => 'Näytä kirjautumislomake',
    'show-register-form' => 'Näytä rekisteröintipainikkeet',
    'sort-order' => 'Lajittelujärjestys',
    'latest-profiles' => 'Uusimmat profiilit',
    'random' => 'satunnainen',
    'candidate-limit' => 'Ehdokasraja',
    'navigation-background' => 'Navigoinnin taustaväri',
    'navigation-text-color' => 'Tekstin väri',
    'footer-background' => 'Alatunnisteen taustaväri',
    'footer-text-color' => 'Alatunnisteen tekstin väri',
    'credits' => 'Laajuus',
    'office-hours' => 'Työaika',
    'social' => 'sosiaalinen',
    'background-color' => 'Taustaväri',
    'background-image' => 'Taustakuva',
    'font-color' => 'Fontin väri',
    'about-us' => 'Meistä',
    'image' => 'Kuva',
    'slide-heading' => 'Dian otsikko',
    'slide-text' => 'Dia-teksti',
    'top-heading' => 'Yläotsikko',
    'sub-heading' => 'Alaotsikko',
    'heading' => 'otsikko',
    'button-text' => 'Painiketeksti',
    'button-url' => 'Painikkeen URL',
    'post-limit' => 'Post Limit',
    'newsletter-code' => 'Uutiskirjekoodi',
    'search' => 'Ehdokashaku',
    'newsletter' => 'tiedote',
    'previous' => 'Edellinen',
    'next' => 'Seuraava',
    'read-more' => 'Lue lisää',
    'view-blog' => 'Näytä blogi',
    'about-heading' => 'Tietoja otsikosta',
    'about-text' => 'Tietoja tekstistä',
    'credits-section' => 'Laajuusosasto',
    'border-color' => 'Reunuksen väri',
    'floating-icons' => 'Näytä kelluvat kuvakkeet?',
    'credits-text' => 'Laajentaa tekstiä',
];