<?php 

return [
    'captcha' => 'Anna oikea koodi CAPTCHA-kuvaan',
    'accepted' => ': Attribuutti on hyväksyttävä.',
    'active_url' => ': Attribuutti ei ole kelvollinen URL.',
    'after' => 'Attribuutin on oltava päivämäärä seuraavan jälkeen: päivämäärä.',
    'after_or_equal' => 'Attribuutin on oltava päivämäärä, joka seuraa tai on yhtä suuri kuin: päivämäärä.',
    'alpha' => ': Attribuutti voi sisältää vain kirjaimia.',
    'alpha_dash' => ': Ominaisuus voi sisältää vain kirjaimia, numeroita, viivoja ja alaviivoja.',
    'alpha_num' => ': Attribuutti voi sisältää vain kirjaimia ja numeroita.',
    'array' => ': Attribuutin on oltava taulukko.',
    'before' => 'Attribuutin on oltava päivämäärä ennen: päivämäärä.',
    'before_or_equal' => 'Attribuutin on oltava päivämäärä ennen tai yhtä suuri kuin: päiväys.',
    'between' => [
        'numeric' => 'Attribuutin on oltava välillä min ja: max.',
        'file' => 'Attribuutin on oltava välillä min ja: max kilotavua.',
        'string' => 'Attribuutin on oltava välillä min ja: max merkkiä.',
        'array' => 'Attribuudissa on oltava välillä: min ja: max kohdetta.',
    ],
    'boolean' => ': Ominaisuuskentän on oltava tosi tai epätosi.',
    'confirmed' => ':attribute Määritteen vahvistus ei vastaa.',
    'date' => ': Attribuutti ei ole kelvollinen päivämäärä.',
    'date_equals' => 'Attribuutin on oltava päivämäärä, joka on yhtä suuri kuin: päivämäärä.',
    'date_format' => 'Attribuutti: ei vastaa muotoa: muotoa.',
    'different' => ': Ominaisuuden ja: muun on oltava erilaisia.',
    'digits' => 'Attribuutin on oltava: numeroita numeroita.',
    'digits_between' => 'Attribuutin on oltava välillä min ja: max numeroa.',
    'dimensions' => ': -Määritteellä on virheelliset kuvan mitat.',
    'distinct' => ': Ominaisuus-kentällä on kaksoisarvo.',
    'email' => ': Attribuutin on oltava kelvollinen sähköpostiosoite.',
    'ends_with' => 'Attribuutin on päätyttävä yhdellä seuraavista:attribute arvot',
    'exists' => 'Valittu: attribuutti on virheellinen.',
    'file' => ': Attribuutin on oltava tiedosto.',
    'filled' => ': Attribuutti-kentällä on oltava arvo.',
    'gt' => [
        'numeric' => 'Attribuutin on oltava suurempi kuin: arvo.',
        'file' => ': Ominaisuuden on oltava suurempi kuin: arvo kilotavua.',
        'string' => 'Attribuutin on oltava suurempi kuin: arvomerkit.',
        'array' => 'Attribuudissa on oltava enemmän kuin: arvo-kohteita.',
    ],
    'gte' => [
        'numeric' => 'Attribuutin on oltava suurempi tai yhtä suuri kuin: arvo.',
        'file' => ': Ominaisuuden on oltava suurempi tai yhtä suuri kuin: arvo kilotavua.',
        'string' => ': Attribuutin on oltava suurempi tai yhtä suuri: arvomerkit.',
        'array' => 'Attribuudilla on oltava: arvoelementtejä tai enemmän.',
    ],
    'image' => ': Attribuutin on oltava kuva.',
    'in' => 'Valittu: attribuutti on virheellinen.',
    'in_array' => ': Ominaisuuskenttää ei ole: muussa.',
    'integer' => 'Attribuutin on oltava kokonaisluku.',
    'ip' => ': Attribuutin on oltava kelvollinen IP-osoite.',
    'ipv4' => ': Attribuutin on oltava kelvollinen IPv4-osoite.',
    'ipv6' => ': Attribuutin on oltava kelvollinen IPv6-osoite.',
    'json' => ': Attribuutin on oltava kelvollinen JSON-merkkijono.',
    'lt' => [
        'numeric' => 'Attribuutin on oltava pienempi kuin: arvo.',
        'file' => ': Ominaisuuden on oltava pienempi kuin: arvo kilotavua.',
        'string' => 'Attribuutin on oltava alle: arvo merkkejä.',
        'array' => 'Attribuudissa on oltava vähemmän kuin: arvokohteet.',
    ],
    'lte' => [
        'numeric' => 'Ominaisuuden: on oltava pienempi tai yhtä suuri kuin: arvo.',
        'file' => ': Ominaisuuden on oltava pienempi tai yhtä suuri kuin: arvo kilotavua.',
        'string' => ': Attribuutin on oltava pienempi tai yhtä suuri: arvomerkkejä.',
        'array' => 'Attribuudissa ei saa olla enemmän kuin: arvo-kohteita.',
    ],
    'max' => [
        'numeric' => ': Attribuutti ei saa olla suurempi kuin: max.',
        'file' => ': Ominaisuus ei saa olla suurempi kuin: korkeintaan kilotavua.',
        'string' => 'Attribuutti ei saa olla suurempi kuin: enimmäismerkit.',
        'array' => 'Attribuudissa ei saa olla enemmän kuin: max kohdetta.',
    ],
    'mimes' => 'Attribuutin on oltava tyyppiä oleva tiedosto:attribute arvot.',
    'mimetypes' => 'Attribuutin on oltava tyyppiä oleva tiedosto:attribute arvot.',
    'min' => [
        'numeric' => ': Ominaisuuden on oltava vähintään: min.',
        'file' => ': Ominaisuuden on oltava vähintään: min kilotavua.',
        'string' => 'Attribuutin on oltava vähintään: min merkkiä.',
        'array' => 'Attribuudissa on oltava vähintään: min kohdetta.',
    ],
    'not_in' => 'Valittu: attribuutti on virheellinen.',
    'not_regex' => ': Attribuutin muoto on virheellinen.',
    'numeric' => 'Attribuutin on oltava numero.',
    'password' => 'Salasana on väärä.',
    'present' => ': Attribuuttikentän on oltava läsnä.',
    'regex' => ': Attribuutin muoto on virheellinen.',
    'required' => ': Attribuuttikenttä on pakollinen.',
    'required_if' => ': Ominaisuuskenttä vaaditaan, kun: muu on: arvo.',
    'required_unless' => ': Ominaisuuskenttä vaaditaan, ellei: muuta ole: arvoissa.',
    'required_with' => ': Ominaisuuskenttä vaaditaan, kun: arvot ovat läsnä.',
    'required_with_all' => ': Ominaisuuskenttä vaaditaan, kun: arvot ovat läsnä.',
    'required_without' => ': Ominaisuuskenttä vaaditaan, kun: arvoja ei ole.',
    'required_without_all' => ': Ominaisuuskenttä vaaditaan, kun mitään arvoista ei ole.',
    'same' => ': Ominaisuuden ja: muun on vastattava toisiaan.',
    'size' => [
        'numeric' => 'Attribuutin on oltava: koko.',
        'file' => ': Ominaisuuden on oltava: koko kilotavua.',
        'string' => 'Attribuutin on oltava: koko merkkejä.',
        'array' => 'Attribuutin tulee sisältää: kokokohteet.',
    ],
    'starts_with' => 'Attribuutin on alkava yhdellä seuraavista:attribute arvot',
    'string' => 'Attribuutin on oltava merkkijono.',
    'timezone' => ': Attribuutin on oltava kelvollinen vyöhyke.',
    'unique' => ': Attribuutti on jo otettu.',
    'uploaded' => ': Ominaisuuden lähettäminen epäonnistui.',
    'url' => ': Attribuutin muoto on virheellinen.',
    'uuid' => ': Attribuutin on oltava kelvollinen UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'tilaustyönä viesti',
        ],
    ],
    'attributes' => '',
];