<?php 

return [
    'dashboard' => 'Tableau de bord',
    'orders' => 'Ordres',
    'employers' => 'Employeurs',
    'candidates' => 'Candidats',
    'invoices' => 'Factures',
    'vacancies' => 'Postes vacants',
    'messaging' => 'Messagerie',
    'blog' => 'Blog',
    'articles' => 'Des articles',
    'forms' => 'Formes',
    'settings' => 'Réglages',
    'general' => 'Général',
    'currency' => 'Devise',
    'language' => 'Langue',
    'email-settings' => 'Paramètres de messagerie',
    'social-login' => 'Connexion sociale',
    'logo-icon' => 'Logo / icône',
    'administrators' => 'Administrateurs',
    'mailchimp-settings' => 'Paramètres Mailchimp',
    'payment-methods' => 'méthodes de payement',
    'order-form' => 'Bon de commande',
    'employer-profile' => 'Profil de l\'employeur',
    'candidate-profile' => 'Profil du candidat',
    'all-candidates' => 'Tous les candidats',
    'shortlisted-candidates' => 'Candidats présélectionnés',
    'employed-candidates' => 'Candidats employés',
    'public-candidates' => 'Candidats publics',
    'create-candidate' => 'Créer un candidat',
    'categories' => 'Les catégories',
    'create-employer' => 'Créer un employeur',
    'all-employers' => 'Tous les employeurs',
    'active-employers' => 'Employeurs actifs',
    'inactive-employers' => 'Employeurs inactifs',
    'employments' => 'Emplacements',
    'order-settings' => 'Paramètres de commande',
    'create-order' => 'Créer une commande',
    'all-orders' => 'Tous les ordres',
    'pending-orders' => 'Les ordres en attente',
    'in-progress-orders' => 'Ordres en cours',
    'completed-orders' => 'Commandes terminées',
    'cancelled-orders' => 'Commandes annulées',
    'emails' => 'Emails',
    'email' => 'Email',
];