<?php 

return [
    'captcha' => 'Veuillez entrer le bon code sur l\'image CAPTCHA',
    'accepted' => 'L\'attribut: doit être accepté.',
    'active_url' => 'L\'attribut: n\'est pas une URL valide.',
    'after' => 'L\'attribut: doit être une date après: date.',
    'after_or_equal' => 'L\'attribut: doit être une date postérieure ou égale à: date.',
    'alpha' => 'L\'attribut: ne peut contenir que des lettres.',
    'alpha_dash' => 'L\'attribut: ne peut contenir que des lettres, des chiffres, des tirets et des traits de soulignement.',
    'alpha_num' => 'L\'attribut: ne peut contenir que des lettres et des chiffres.',
    'array' => 'L\'attribut: doit être un tableau.',
    'before' => 'L\'attribut: doit être une date antérieure à: date.',
    'before_or_equal' => 'L\'attribut: doit être une date antérieure ou égale à: date.',
    'between' => [
        'numeric' => 'L\'attribut: doit être compris entre: min et: max.',
        'file' => 'L\'attribut: doit être compris entre: min et: max kilo-octets.',
        'string' => 'L\'attribut: doit être compris entre: min et: max caractères.',
        'array' => 'L\'attribut: doit avoir entre: min et: max éléments.',
    ],
    'boolean' => 'Le champ d\'attribut: doit être vrai ou faux.',
    'confirmed' => 'La: confirmation de l\'attribut ne correspond pas.',
    'date' => 'L\'attribut: n\'est pas une date valide.',
    'date_equals' => 'L\'attribut: doit être une date égale à: date.',
    'date_format' => 'L\'attribut: ne correspond pas au format: format.',
    'different' => 'L\'attribut: et: autre doivent être différents.',
    'digits' => 'L\'attribut: doit être: chiffres chiffres.',
    'digits_between' => 'L\'attribut: doit être compris entre: min et: max chiffres.',
    'dimensions' => 'L\'attribut: a des dimensions d\'image non valides.',
    'distinct' => 'Le champ d\'attribut: a une valeur en double.',
    'email' => 'L\'attribut: doit être une adresse e-mail valide.',
    'ends_with' => 'L\'attribut: doit se terminer par l\'un des éléments suivants:attribute values',
    'exists' => 'L\'attribut: sélectionné n\'est pas valide.',
    'file' => 'L\'attribut: doit être un fichier.',
    'filled' => 'Le champ d\'attribut: doit avoir une valeur.',
    'gt' => [
        'numeric' => 'L\'attribut: doit être supérieur à: value.',
        'file' => 'L\'attribut: doit être supérieur à: valeur kilo-octets.',
        'string' => 'L\'attribut: doit être supérieur à: les caractères de valeur.',
        'array' => 'L\'attribut: doit avoir plus de: éléments de valeur.',
    ],
    'gte' => [
        'numeric' => 'L\'attribut: doit être supérieur ou égal à: value.',
        'file' => 'L\'attribut: doit être supérieur ou égal à: kilo-octets de valeur.',
        'string' => 'L\'attribut: doit être supérieur ou égal à: caractères de valeur.',
        'array' => 'L\'attribut: doit avoir: des éléments de valeur ou plus.',
    ],
    'image' => 'L\'attribut: doit être une image.',
    'in' => 'L\'attribut: sélectionné n\'est pas valide.',
    'in_array' => 'Le champ d\'attribut: n\'existe pas dans: autre.',
    'integer' => 'L\'attribut: doit être un entier.',
    'ip' => 'L\'attribut: doit être une adresse IP valide.',
    'ipv4' => 'L\'attribut: doit être une adresse IPv4 valide.',
    'ipv6' => 'L\'attribut: doit être une adresse IPv6 valide.',
    'json' => 'L\'attribut: doit être une chaîne JSON valide.',
    'lt' => [
        'numeric' => 'L\'attribut: doit être inférieur à: value.',
        'file' => 'L\'attribut: doit être inférieur à: valeur kilo-octets.',
        'string' => 'L\'attribut: doit être inférieur à: les caractères de valeur.',
        'array' => 'L\'attribut: doit avoir moins de: éléments de valeur.',
    ],
    'lte' => [
        'numeric' => 'L\'attribut: doit être inférieur ou égal à: value.',
        'file' => 'L\'attribut: doit être inférieur ou égal à: kilo-octets de valeur.',
        'string' => 'L\'attribut: doit être inférieur ou égal à: caractères de valeur.',
        'array' => 'L\'attribut: ne doit pas avoir plus de: éléments de valeur.',
    ],
    'max' => [
        'numeric' => 'L\'attribut: ne doit pas être supérieur à: max.',
        'file' => 'L\'attribut: ne doit pas être supérieur à: kilo-octets max.',
        'string' => 'L\'attribut: ne doit pas être supérieur à: caractères max.',
        'array' => 'L\'attribut: ne peut pas avoir plus de: max éléments.',
    ],
    'mimes' => 'L\'attribut: doit être un fichier de type:attribute valeurs.',
    'mimetypes' => 'L\'attribut: doit être un fichier de type:attribute valeurs.',
    'min' => [
        'numeric' => 'L\'attribut: doit être au moins: min.',
        'file' => 'L\'attribut: doit être d\'au moins: min kilo-octets.',
        'string' => 'L\'attribut: doit contenir au moins: min caractères.',
        'array' => 'L\'attribut: doit avoir au moins: min éléments.',
    ],
    'not_in' => 'L\'attribut: sélectionné n\'est pas valide.',
    'not_regex' => 'Le format d\'attribut: n\'est pas valide.',
    'numeric' => 'L\'attribut: doit être un nombre.',
    'password' => 'Le mot de passe est incorrect.',
    'present' => 'Le champ d\'attribut: doit être présent.',
    'regex' => 'Le format d\'attribut: n\'est pas valide.',
    'required' => 'Le champ d\'attribut: est obligatoire.',
    'required_if' => 'Le champ: attribut est obligatoire lorsque: autre est: valeur.',
    'required_unless' => 'Le champ: attribut est obligatoire sauf si: autre est dans: valeurs.',
    'required_with' => 'Le champ: attribute est obligatoire lorsque: values ​​est présent.',
    'required_with_all' => 'Le champ: attribut est obligatoire lorsque: des valeurs sont présentes.',
    'required_without' => 'Le champ: attribute est obligatoire lorsque: values ​​n\'est pas présent.',
    'required_without_all' => 'Le champ d\'attribut: est obligatoire lorsqu\'aucune des valeurs: n\'est présente.',
    'same' => 'L\'attribut: et: autre doivent correspondre.',
    'size' => [
        'numeric' => 'L\'attribut: doit être: taille.',
        'file' => 'L\'attribut: doit être: size kilo-octets.',
        'string' => 'L\'attribut: doit être: caractères de taille.',
        'array' => 'L\'attribut: doit contenir: des éléments de taille.',
    ],
    'starts_with' => 'L\'attribut: doit commencer par l\'un des éléments suivants:attribute values',
    'string' => 'L\'attribut: doit être une chaîne.',
    'timezone' => 'L\'attribut: doit être une zone valide.',
    'unique' => 'L\'attribut: a déjà été pris.',
    'uploaded' => 'L\'attribut: n\'a pas pu être téléchargé.',
    'url' => 'Le format d\'attribut: n\'est pas valide.',
    'uuid' => 'L\'attribut: doit être un UUID valide.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'message personnalisé',
        ],
    ],
    'attributes' => '',
];