<?php
return [
        'welcome-heading'=>'Welcome Heading',
        'welcome-message'=>'Welcome Message',
        'show-order-form'=>'Show Order Form Button',
        'show-browse-profiles'=>'Show Browse Profiles Button',
        'text'=>'Text',
        'show-login-form'=>'Show Login Form',
        'show-register-form'=>'Show Registration Buttons',
        'sort-order'=>'Sort Order',
        'latest-profiles'=>'Latest Profiles',
        'random'=>'Random',
        'candidate-limit'=>'Candidate Limit',
        'navigation-background'=>'Navigation Background Color',
        'navigation-text-color'=>'Navigation Text Color',
        'footer-background'=>'Footer Background Color',
        'footer-text-color'=>'Footer Text Color',
        'credits'=>'Credits',
        'office-hours'=>'Office Hours',
        'social'=>'Social',
        'background-color'=>'Background Color',
    'background-image'=>'Background Image',
    'font-color'=>'Font Color',
    'about-us'=>'About Us',
    'image'=>'Image',
    'slide-heading'=>'Slide Heading',
    'slide-text'=>'Slide Text',
    'top-heading'=>'Top Heading',
    'sub-heading'=>'Sub Heading',
    'heading'=>'Heading',
    'button-text'=>'Button Text',
    'button-url'=>'Button URL',
    'post-limit'=>'Post Limit',
    'newsletter-code'=>'Newsletter Code',
    'search'=>'Candidate Search',
    'newsletter'=>'Newsletter',
    'previous'=>'Previous',
    'next'=>'Next',
    'read-more'=>'Read More',
    'view-blog'=>'View Blog',
    'about-heading'=>'About Heading',
    'about-text'=>'About Text',
    'credits-section'=>'Credits Section',
    'border-color'=>'Border Color',
    'floating-icons'=>'Show floating icons?',
    'credits-text'=>'Credits Text'

];