<?php

return [
    'app-description'=>'Great looking template for all types of agencies',
    'slideshow'=>'Slideshow',
    'slideshow-desc'=>'The slideshow on the homepage',
    'services'=>'Services',
    'services-desc'=>'The services we offer section on the homepage',
    'homepage-about'=>'Homepage About Us',
    'homepage-about-desc'=>'The About Us section on the homepage',
    'homepage-candidates'=>'Homepage Candidates',
    'homepage-candidates-desc'=>'Enable or disable showing candidate profiles on the homepage',
    'contact-us'=>'Contact Us',
    'top-bar'=>'Top Bar',
    'tob-bar-desc'=>'The Top Bar of all the site pages',
    'nav-bar'=>'Navigation Bar',
    'nav-bar-desc'=>'The main site navigation bar',
    'testimonials'=>'Testimonials',
    'testimonials-desc'=>'Testimonials section on the homepage',
    'blog'=>'Blog',
    'blog-desc'=>'The blog section on the homepage',
    'footer-gallery'=>'Footer Gallery',
    'footer-gallery-desc'=>'The Gallery of images on the Footer',
    'welcome'=>'Welcome',
    'footer'=>'Footer',
    'footer-desc'=>'The footer area of the site',
    'place-order'=>'Place Order',
    'office-address'=>'Office Address',
    'email'=>'Email',
    'heading-color'=>'Slide Heading Font Color',
    'text-color'=>'Text Color',
    'button-text'=>'Button Text',
    'order-button'=>'Order Button',
    'homepage-services'=>'Homepage Services',
    'homepage-services-desc'=>'The services section of the Homepage',
    'demo'=>'Demo',
    'service'=>'Service',
    'information'=>'Information',
    'link'=>'Link',
    'contact-form'=>'Contact Form',
    'contact-form-desc'=>'The contact form at the footer of all site pages',
    'stars'=>'Stars',
    'testimonial'=>'Testimonial',
    'send'=>'Send',
    'page-title'=>'Page Title',
    'page-title-desc'=>'The page title on all the site pages (apart from homepage)',
    'background-image'=>'Background image',
    'enter-message'=>'Enter Message',
    'enter-your-name'=>'Enter your name',
    'enter-email'=>'Enter email address',
    'enter-subject'=>'Enter Subject',
    'address'=>'Address',
    'recent-posts'=>'Recent Posts'

];
