<?php 

return [
    'dashboard' => 'Instrumententafel',
    'orders' => 'Aufträge',
    'employers' => 'Arbeitgeber',
    'candidates' => 'Kandidaten',
    'invoices' => 'Rechnungen',
    'vacancies' => 'Stellenangebote',
    'messaging' => 'Messaging',
    'blog' => 'Blog',
    'articles' => 'Artikel',
    'forms' => 'Formen',
    'settings' => 'die Einstellungen',
    'general' => 'Allgemeines',
    'currency' => 'Währung',
    'language' => 'Sprache',
    'email-settings' => 'Email Einstellungen',
    'social-login' => 'Social Login',
    'logo-icon' => 'Logo / Symbol',
    'administrators' => 'Administratoren',
    'mailchimp-settings' => 'Mailchimp-Einstellungen',
    'payment-methods' => 'Zahlungsmethoden',
    'order-form' => 'Bestellformular',
    'employer-profile' => 'Arbeitgeberprofil',
    'candidate-profile' => 'Kandidaten Profil',
    'all-candidates' => 'Alle Kandidaten',
    'shortlisted-candidates' => 'Kandidaten in die engere Wahl',
    'employed-candidates' => 'Angestellte Kandidaten',
    'public-candidates' => 'Öffentliche Kandidaten',
    'create-candidate' => 'Kandidaten erstellen',
    'categories' => 'Kategorien',
    'create-employer' => 'Arbeitgeber erstellen',
    'all-employers' => 'Alle Arbeitgeber',
    'active-employers' => 'Aktive Arbeitgeber',
    'inactive-employers' => 'Inaktive Arbeitgeber',
    'employments' => 'Platzierungen',
    'order-settings' => 'Auftragseinstellungen',
    'create-order' => 'Bestellung anlegen',
    'all-orders' => 'Alle Bestellungen',
    'pending-orders' => 'Ausstehende Bestellungen',
    'in-progress-orders' => 'In Bearbeitung Bestellungen',
    'completed-orders' => 'Abgeschlossene Bestellungen',
    'cancelled-orders' => 'Stornierte Bestellungen',
    'emails' => 'E-Mails',
    'email' => 'Email',
];