<?php 

return [
    'captcha' => 'Sisestage CAPTCHA pildile õige kood',
    'accepted' => 'Atribuut: peab olema aktsepteeritud.',
    'active_url' => 'Atribuut: URL pole kehtiv.',
    'after' => 'Atribuut: peab olema kuupäev pärast kuupäeva.',
    'after_or_equal' => 'Atribuut: peab olema kuupäev pärast kuupäeva või sellega võrdne.',
    'alpha' => 'Atribuut: võib sisaldada ainult tähti.',
    'alpha_dash' => 'Atribuut: võib sisaldada ainult tähti, numbreid, kriipsusid ja allakriipsutusi.',
    'alpha_num' => 'Atribuut: võib sisaldada ainult tähti ja numbreid.',
    'array' => 'Atribuut: peab olema massiiv.',
    'before' => 'Atribuut: peab olema kuupäev enne kuupäeva: kuupäev.',
    'before_or_equal' => 'Atribuut: peab olema kuupäev enne kuupäeva või sellega võrdne: kuupäev.',
    'between' => [
        'numeric' => 'Atribuut: peab olema vahemikus: min ja: max.',
        'file' => 'Atribuut: peab jääma vahemikku: min kuni: max kilobaiti.',
        'string' => 'Atribuut: peab olema vahemikus: min ja: max tähemärki.',
        'array' => 'Atribuudil peab üksuste vahel olema: min ja: max.',
    ],
    'boolean' => 'Atribuudi väli peab olema tõene või vale.',
    'confirmed' => 'Atribuudi kinnitus ei kattu.',
    'date' => 'Atribuut: pole kehtiv kuupäev.',
    'date_equals' => 'Atribuut: peab olema kuupäev, mis on võrdne kuupäevaga.',
    'date_format' => 'Atribuut: ei vasta vormingule: vormingule.',
    'different' => 'Atribuut: ja: muu peavad olema erinevad.',
    'digits' => 'Atribuut: peab olema: numbrikohad.',
    'digits_between' => 'Atribuut: peab olema vahemikus: min ja: max numbrit.',
    'dimensions' => 'Atribuudil on valed kujutise mõõtmed.',
    'distinct' => 'Atribuudi väljal on duplikaatväärtus.',
    'email' => 'Atribuut: peab olema kehtiv e-posti aadress.',
    'ends_with' => 'Atribuut: peab lõppema ühega järgmistest:attribute väärtused',
    'exists' => 'Valitud: atribuut on kehtetu.',
    'file' => 'Atribuut: peab olema fail.',
    'filled' => 'Atribuudi väljal peab olema väärtus.',
    'gt' => [
        'numeric' => 'Atribuut: peab olema suurem kui: väärtus.',
        'file' => 'Atribuut: peab olema suurem kui: väärtus kilobaiti.',
        'string' => 'Atribuut: peab olema suurem kui: väärtusmärgid.',
        'array' => 'Atribuudil peab olema rohkem kui: väärtuse üksusi.',
    ],
    'gte' => [
        'numeric' => 'Atribuut: peab olema suurem või võrdne: väärtusega.',
        'file' => 'Atribuut: peab olema suurem või võrdne: väärtus kilobaiti.',
        'string' => 'Atribuut: peab olema suurem või võrdne: väärtusmärke.',
        'array' => 'Atribuudil peab olema: väärtusüksusi või rohkem.',
    ],
    'image' => 'Atribuut: peab olema pilt.',
    'in' => 'Valitud: atribuut on kehtetu.',
    'in_array' => 'Atribuudi välja ei eksisteeri kaustas: muu.',
    'integer' => 'Atribuut: peab olema täisarv.',
    'ip' => 'Atribuut: peab olema kehtiv IP-aadress.',
    'ipv4' => 'Atribuut: peab olema kehtiv IPv4-aadress.',
    'ipv6' => 'Atribuut: peab olema kehtiv IPv6-aadress.',
    'json' => 'Atribuut: peab olema kehtiv JSON-string.',
    'lt' => [
        'numeric' => 'Atribuut: peab olema väiksem kui: väärtus.',
        'file' => 'Atribuut: peab olema väiksem kui: väärtus kilobaiti.',
        'string' => 'Atribuut: peab olema väiksem kui: väärtusmärgid.',
        'array' => 'Atribuudil peab olema vähem kui: väärtuse üksusi.',
    ],
    'lte' => [
        'numeric' => 'Atribuut: väärtus peab olema väiksem või sellega võrdne: väärtus.',
        'file' => 'Atribuut: peab olema väiksem või võrdne: väärtus kilobaiti.',
        'string' => 'Atribuut: peab olema väiksem või võrdne: väärtusmärke.',
        'array' => 'Atribuudil ei tohi olla rohkem kui: väärtuse üksusi.',
    ],
    'max' => [
        'numeric' => 'Atribuut: ei tohi olla suurem kui: max.',
        'file' => 'Atribuut: ei tohi olla suurem kui: max kilobaiti.',
        'string' => 'Atribuut: ei tohi olla suurem kui: max tähemärki.',
        'array' => 'Atribuudil ei tohi olla rohkem kui: max üksust.',
    ],
    'mimes' => 'Atribuut: peab olema faili tüüp:attribute väärtused.',
    'mimetypes' => 'Atribuut: peab olema faili tüüp:attribute väärtused.',
    'min' => [
        'numeric' => 'Atribuut: peab olema vähemalt: min.',
        'file' => 'Atribuut: peab olema vähemalt: min kilobaiti.',
        'string' => 'Atribuut: peab olema vähemalt: min tähemärki.',
        'array' => 'Atribuudil peab olema vähemalt: min üksusi.',
    ],
    'not_in' => 'Valitud: atribuut on kehtetu.',
    'not_regex' => 'Atribuudi vorming on vale.',
    'numeric' => 'Atribuut: peab olema number.',
    'password' => 'Parool on vale.',
    'present' => 'Atribuudi väli peab olema olemas.',
    'regex' => 'Atribuudi vorming on vale.',
    'required' => 'Atribuudi väli on kohustuslik.',
    'required_if' => 'Väli: atribuut on kohustuslik, kui: muu on: väärtus.',
    'required_unless' => 'Väli: atribuut on kohustuslik, välja arvatud juhul, kui: muu on väärtustes.',
    'required_with' => 'Atribuudi väli on nõutav, kui: väärtused on olemas.',
    'required_with_all' => 'Väli: atribuut on nõutav, kui: väärtused on olemas.',
    'required_without' => 'Atribuudi väli on nõutav, kui: väärtusi pole.',
    'required_without_all' => 'Atribuudi väli on nõutav, kui ühtegi väärtust pole.',
    'same' => 'Atribuut: ja muu peavad vastama.',
    'size' => [
        'numeric' => 'Atribuut: atribuut peab olema: suurus.',
        'file' => 'Atribuut: peab olema: suurus kilobaiti.',
        'string' => 'Atribuut: peab olema: tähemärki.',
        'array' => 'Atribuut: peab sisaldama: suuruse üksusi.',
    ],
    'starts_with' => 'Atribuut: peab algama ühega järgmistest:attribute väärtused',
    'string' => 'Atribuut: peab olema string.',
    'timezone' => 'Atribuut: peab olema kehtiv tsoon.',
    'unique' => 'Atribuut: on juba võetud.',
    'uploaded' => 'Atribuuti ei õnnestunud üles laadida.',
    'url' => 'Atribuudi vorming on vale.',
    'uuid' => 'Atribuut: peab olema kehtiv UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'kohandatud teade',
        ],
    ],
    'attributes' => '',
];