<?php 

return [
    'dashboard' => 'painel de controle',
    'orders' => 'Encomendas',
    'employers' => 'Empregadores',
    'candidates' => 'Candidatos',
    'invoices' => 'Faturas',
    'vacancies' => 'Vagas',
    'messaging' => 'Mensagens',
    'blog' => 'Blog',
    'articles' => 'Artigos',
    'forms' => 'Formulários',
    'settings' => 'Definições',
    'general' => 'Geral',
    'currency' => 'Moeda',
    'language' => 'Língua',
    'email-settings' => 'Configurações de email',
    'social-login' => 'Login Social',
    'logo-icon' => 'Logo / Ícone',
    'administrators' => 'Administradores',
    'mailchimp-settings' => 'Configurações do Mailchimp',
    'payment-methods' => 'Métodos de Pagamento',
    'order-form' => 'Formulário de Pedido',
    'employer-profile' => 'Perfil do empregador',
    'candidate-profile' => 'Perfil do candidato',
    'all-candidates' => 'Todos os candidatos',
    'shortlisted-candidates' => 'Candidatos pré-selecionados',
    'employed-candidates' => 'Candidatos Empregados',
    'public-candidates' => 'Candidatos Públicos',
    'create-candidate' => 'Criar candidato',
    'categories' => 'Categorias',
    'create-employer' => 'Criar Empregador',
    'all-employers' => 'Todos os empregadores',
    'active-employers' => 'Empregadores ativos',
    'inactive-employers' => 'Empregadores inativos',
    'employments' => 'Canais',
    'order-settings' => 'Configurações de pedidos',
    'create-order' => 'Criar pedido',
    'all-orders' => 'Todos os pedidos',
    'pending-orders' => 'Ordens pendentes',
    'in-progress-orders' => 'Ordens em andamento',
    'completed-orders' => 'Encomendas concluídas',
    'cancelled-orders' => 'Pedidos cancelados',
    'emails' => 'Emails',
    'email' => 'O email',
];