<?php 

return [
    'dashboard' => 'لوحة القيادة',
    'orders' => 'الطلب #٪ s',
    'employers' => 'أرباب العمل',
    'candidates' => 'المرشحون',
    'invoices' => 'فواتير',
    'vacancies' => 'الشواغر',
    'messaging' => 'المراسلة',
    'blog' => 'مدونة',
    'articles' => 'مقالات',
    'forms' => 'نماذج',
    'settings' => 'الإعدادات',
    'general' => 'جنرال لواء',
    'currency' => 'عملة',
    'language' => 'لغة',
    'email-settings' => 'إعدادات البريد الإلكتروني',
    'social-login' => 'تسجيل الدخول الاجتماعي',
    'logo-icon' => 'الشعار / الرمز',
    'administrators' => 'المسؤولون',
    'mailchimp-settings' => 'إعدادات Mailchimp',
    'payment-methods' => 'طرق الدفع',
    'order-form' => 'نموذج الطلب',
    'employer-profile' => 'الملف الشخصي لصاحب العمل',
    'candidate-profile' => 'ملف المرشح',
    'all-candidates' => 'جميع المرشحين',
    'shortlisted-candidates' => 'قائمة المرشحين المختصرة',
    'employed-candidates' => 'المرشحين العاملين',
    'public-candidates' => 'المرشحون العموميون',
    'create-candidate' => 'إنشاء مرشح',
    'categories' => 'التصنيفات',
    'create-employer' => 'إنشاء صاحب عمل',
    'all-employers' => 'جميع أصحاب العمل',
    'active-employers' => 'أصحاب العمل النشطين',
    'inactive-employers' => 'أرباب العمل غير النشطين',
    'employments' => 'المواضع',
    'order-settings' => 'إعدادات الطلب',
    'create-order' => 'إنشاء النظام',
    'all-orders' => 'جميع الطلبات',
    'pending-orders' => 'الأوامر المعلقة',
    'in-progress-orders' => 'أوامر قيد التنفيذ',
    'completed-orders' => 'أوامر مكتملة',
    'cancelled-orders' => 'الطلبات الملغاة',
    'emails' => 'رسائل البريد الإلكتروني',
    'email' => 'البريد الإلكتروني',
];