<?php 

return [
    'welcome-heading' => 'عنوان الترحيب',
    'welcome-message' => 'رسالة الترحيب',
    'show-order-form' => 'إظهار زر نموذج الطلب',
    'show-browse-profiles' => 'إظهار زر استعراض ملفات التعريف',
    'text' => 'نص',
    'show-login-form' => 'إظهار نموذج تسجيل الدخول',
    'show-register-form' => 'إظهار أزرار التسجيل',
    'sort-order' => 'امر ترتيب',
    'latest-profiles' => 'أحدث ملفات التعريف',
    'random' => 'عشوائي',
    'candidate-limit' => 'حد المرشح',
    'navigation-background' => 'لون خلفية التنقل',
    'navigation-text-color' => 'لون نص التنقل',
    'footer-background' => 'لون خلفية التذييل',
    'footer-text-color' => 'لون نص التذييل',
    'credits' => 'ائتمانات',
    'office-hours' => 'ساعات العمل',
    'social' => 'اجتماعي',
    'background-color' => 'لون الخلفية',
    'background-image' => 'الصورة الخلفية',
    'font-color' => 'لون الخط',
    'about-us' => 'معلومات عنا',
    'image' => 'صورة',
    'slide-heading' => 'عنوان الشريحة',
    'slide-text' => 'نص الشريحة',
    'top-heading' => 'عنوان علوي',
    'sub-heading' => 'العنوان الفرعي',
    'heading' => 'عنوان',
    'button-text' => 'زر كتابة',
    'button-url' => 'عنوان URL للزر',
    'post-limit' => 'حد المشاركة',
    'newsletter-code' => 'رمز النشرة الإخبارية',
    'search' => 'بحث المرشح',
    'newsletter' => 'النشرة الإخبارية',
    'previous' => 'السابق',
    'next' => 'التالى',
    'read-more' => 'اقرأ أكثر',
    'view-blog' => 'عرض المدونة',
    'about-heading' => 'حول العنوان',
    'about-text' => 'حول النص',
    'credits-section' => 'قسم الاعتمادات',
    'border-color' => 'لون الحدود',
    'floating-icons' => 'هل تريد إظهار الرموز العائمة؟',
    'credits-text' => 'نص الاعتمادات',
];